---
title: "Cody"
author: "Cody Spiegel"
date: "4/22/2022"
output: word_document
---

```{r setup chunk, setup, include = FALSE, cache=FALSE, message=FALSE, warning=FALSE}
if (!require('knitr')) install.packages('knitr'); library('knitr')
knitr::opts_chunk$set(warning=FALSE, message=FALSE, fig.align='center')

# load packages
if (!require("pacman")) install.packages("pacman") # for rapid install if not in library

# use pacman to load all the packages you are missing!
pacman::p_load('knitr', 'lme4', 'lmerTest', 'tidyverse', 'magrittr', 'effects', 'plyr', 'dplyr', 
               'plotrix', 'car',"gridExtra", "cowplot", "tools")
Fig.formatting<-(theme_classic()) +
  theme(text=element_text(size=14),
        legend.text.align = 0,
        panel.border = element_rect(fill=NA, colour = "black", size=1),
        aspect.ratio=1, 
        axis.ticks.length=unit(0.25, "cm"),
        axis.text.y=element_text(
        margin=unit(c(0.5, 0.5, 0.5, 0.5), "cm"), colour="black", size=12), 
        axis.text.x=element_text(
        margin=unit(c(0.5, 0.5, 0.5, 0.5), "cm"), colour="black", size=12)) +
  theme(legend.key.size = unit(0.4, "cm")) +
  theme(aspect.ratio=1.3) +
  theme(panel.spacing=unit(c(0, 0, 0, 0), "cm"))


```

###DOC  
import and do a loop to clean up all files and make stacked data in single df
```{r}
## import treatment IDs
IDs<-read.csv("/Users/tobyspiegel2/Desktop/My_pyromania/Pyromania/data/treatment.IDs.csv")

##### grab files in a list
Total.DOC.files <- list.files(path="/Users/tobyspiegel2/Desktop/My_pyromania/Pyromania/data/DOC.TN", pattern = "csv$", full.names = T)

##### what are the file names, sans extensions using package 'tools'
file.names<-file_path_sans_ext(list.files(path="/Users/tobyspiegel2/Desktop/My_pyromania/Pyromania/data/DOC.TN", pattern = "csv$", full.names = F))

############ formatting all data in for loop
  for(i in 1:length(Total.DOC.files))
    {
  data<-read.csv(Total.DOC.files[i], sep=",")
  data<-data[,c(1,3,4)] # removed columns we don't need
  data$File<-Total.DOC.files[i]
  colnames(data)<-c("Tank", "DOC..mg.L", "TN..mg.L", "File")
  data$Tank<- IDs$Tank
  data$Tank<-as.numeric(as.character(data$Tank)) # make the column of samples all numeric
  data <- data[!is.na(as.numeric(as.character(data$Tank))),] # remove all rows that aren't numeric/tanks
  data$Treatment<-IDs$Treatment
  data$plant.mass..g<-IDs$plant.mass..g
  make.names(assign(paste(file.names[i], sep=""), data)) # make the file name the name of new df for loop df
  }

########## this is the end of the loop

#Combine files from loop to single df
DOC.df<-rbind(DOC_T0, DOC_T1, DOC_T2, DOC_T3, DOC_T4)
DOC.df2=rbind(DOC_T1, DOC_T2, DOC_T3, DOC_T4)
DOC.df$Treatment=as.factor(DOC.df$Treatment)

DOC.df$File<-substr(DOC.df$File, 64, 74) 
DOC.df2$File<-substr(DOC.df2$File, 64, 74) 
# alternative way to code the above
#give the 10th-24th character of the file name, removing the rest
#DOC.df$File<-substr(DOC.df$File, 13, 27) 

#alternatively
# remove the 9 letters ('^.) at start 
# remove the 4 letters (.$') at end
#DOC.df$File<-gsub('^.........|....$', '', DOC.df$File) 

# if equals DOC_T0_11052021 then, T0, if not then T1
DOC.df$Time.point<- as.factor(ifelse(DOC.df$File=="DOC_T0.csv", "T0",
         ifelse (DOC.df$File=="DOC_T1.csv", "T1",
           ifelse (DOC.df$File=="DOC_T2.csv", "T2", 
                   ifelse(DOC.df$File=="DOC_T3.csv", "T3", "T4")))))

DOC.df2$Time.point<- as.factor(
         ifelse (DOC.df2$File=="DOC_T1.csv", "T1",
           ifelse (DOC.df2$File=="DOC_T2.csv", "T2", 
                   ifelse(DOC.df2$File=="DOC_T3.csv", "T3", "T4"))))

#rearrange
library(dplyr)
DOC.df<- DOC.df %>% 
  dplyr::select(File, Time.point, Treatment, Tank, plant.mass..g, DOC..mg.L, TN..mg.L) 

DOC.df2<- DOC.df2 %>% 
  dplyr::select(File, Time.point, Treatment, Tank, plant.mass..g, DOC..mg.L, TN..mg.L) 


#visualize
ggplot(DOC.df, aes(x = plant.mass..g, y = DOC..mg.L, colour = Treatment)) +
    geom_point() +
    facet_grid(~Time.point)+
    geom_smooth(method = 'loess', se = FALSE) 

#x axis time
#y doc
#shape treatment
#color mass
DOC.df2=mutate(DOC.df2, oTreatment= ordered(Treatment, levels= c("burned", "unburned")))
DOC.df2=mutate(DOC.df2, oTime.point= ordered(Time.point, levels= c("T1", "T2", "T3", "T4")))
DOC.df2$oTreatment=as.factor(DOC.df2$oTreatment)
DOC.df2$oTime.point=as.factor(DOC.df2$oTime.point)




```
DOC concentration Figure
```{r fig.cap="scatter plots for sepal length, sepal width and petal length"}
DOC.T0<-ggplot(DOC.df[(DOC.df$Time.point=="T0"),], aes(x=plant.mass..g, y=DOC..mg.L, color=Treatment)) +
  geom_point() +
  scale_color_manual(values = c("orange", "purple")) + 
  geom_smooth(method=loess, aes(fill=Treatment), alpha=0.1) +
  coord_cartesian(ylim=c(0, 60)) +
  ggtitle("Time-0") +
  xlab("")+
  ylab("DOC (mg/L)") +
  Fig.formatting


DOC.T1<-ggplot(DOC.df[(DOC.df$Time.point=="T1"),], aes(x=plant.mass..g, y=DOC..mg.L, color=Treatment)) + 
  geom_point() +
  scale_color_manual(values = c("orange", "purple")) + 
  geom_smooth(method=loess, aes(fill=Treatment), alpha=0.1) +
  coord_cartesian(ylim=c(0, 60)) +
  ggtitle("Time-1") +
  xlab("")+
  ylab("")+
  Fig.formatting
  
DOC.T2<-ggplot(DOC.df[(DOC.df$Time.point=="T2"),], aes(x=plant.mass..g, y=DOC..mg.L, color=Treatment)) + 
  geom_point() +
  scale_color_manual(values = c("orange", "purple")) + 
  geom_smooth(method=loess, aes(fill=Treatment), alpha=0.1) +
  coord_cartesian(ylim=c(0, 60)) +
  ggtitle("Time-2") +
  xlab("plant material (g)") +
  ylab("")+
  Fig.formatting

  
DOC.T3<-ggplot(DOC.df[(DOC.df$Time.point=="T3"),], aes(x=plant.mass..g, y=DOC..mg.L, color=Treatment)) + 
  geom_point() +
  scale_color_manual(values = c("orange", "purple")) + 
  geom_smooth(method=loess, aes(fill=Treatment), alpha=0.1) +
  coord_cartesian(ylim=c(0, 60)) +
  ggtitle("Time-3") +
  xlab("")+
  ylab("")+
  Fig.formatting

DOC.T4<-ggplot(DOC.df[(DOC.df$Time.point=="T4"),], aes(x=plant.mass..g, y=DOC..mg.L, color=Treatment)) + 
  geom_point() +
  scale_color_manual(values = c("orange", "purple")) + 
  geom_smooth(method=loess, aes(fill=Treatment), alpha=0.1) +
  coord_cartesian(ylim=c(0, 60)) +
  ggtitle("Time-4") +
  xlab("")+
  ylab("")+
  Fig.formatting


extract.legend <- get_legend(
  # create some space to the left of the legend
  DOC.T0 + theme(legend.box.margin = margin(0, 0, 0, 10)))


DOC.plots<-plot_grid(
  DOC.T0+ theme(legend.position = "none"),
  DOC.T1+ theme(legend.position = "none"),
  DOC.T2+ theme(legend.position = "none"),
  DOC.T3+ theme(legend.position = "none"),
  DOC.T4+ theme(legend.position = "none"),
  extract.legend,
  rel_widths = c(15,15,15,15, 15, 8), ncol=6)


plot_grid(
  ggdraw(add_sub(DOC.plots, "Fig 1. Measured dissolved organic carbon (DOC) concentrations across five time points for both treatments. Time-0 represents baseline DOC concentrations \nprior to the start of the experiment.", x=0.01, hjust=0)), ncol = 1)


ggsave("figures/fig1.DOC.pdf", height=5, width=14)


  

```

DOC analysis
```{r}
library(mgcv)
library(gratia)
#####
ggplot(DOC.df)+
  geom_point(aes(x=plant.mass..g,y=DOC..mg.L,color=Treatment,shape=Time.point))+
  geom_smooth(aes(x=plant.mass..g, y=DOC..mg.L, color=Treatment), method = "gam", formula = y ~ s(x, bs="tp"))
#DOC plant mass varying by treatment and sampling period. The main question is how do treatment and plant mass affect DOC while controlling for the time period. 
#We can use this model to answer our question: 
#In lme4, a random slope with correlated random intercept is included with the syntax (1+Treatment|Time.point), and a random slope with no variation in intercept is included with the syntax (0+Treatment|Time.point) where time point is the random effect in question, and the random slope is built for each level of Treatment). 

#In mgcv, a random slope is included with the syntax s(Time.point,Treatment, bs=“re”). Here, time point is the random effect, the random slope is being built over treatment, and bs=“re” tells R that the basis function here is a random effect structure. Note that this is the analog of (0+Treamtment|TIme.point) for lme4 syntax. The structure (1+Treatment|Time.point) is not possible in mgcv, so a random slope and random intercept must be specified.
#This will be our null model
m1.gam=gam(DOC..mg.L~ Treatment + s(plant.mass..g, by = Treatment) + s(Time.point, bs = "re"), data = DOC.df, method = "REML")
summary(m1.gam)
draw(m1.gam)

m2.gam=gam(DOC..mg.L~ Treatment + s(plant.mass..g, by = Treatment)+ s(Time.point, Treatment, bs = "re"), data = DOC.df, method = "REML")
summary(m2.gam)

m3.gam=gam(DOC..mg.L~ Treatment + s(plant.mass..g, by = Treatment) + s(Time.point, bs = "re")+ s(Time.point, Treatment, bs = "re"), data = DOC.df, method = "REML")
summary(m3.gam)

AIC(m1.gam, m2.gam, m3.gam)
```


```{r}
#So far, the random effects included all have had the same general shape across random variables. That is, the random intercepts move the splines up and down, but have the same shape. Random slopes tilt the splines, but do not change their general shape.

#With GAMs, we can actually include non-linear random effects i.e., individual variability can be taken into account across plant mass or another smoothed predictor. These non-linear random effects are called “factor smooths” and shown as s(plant.mass..g, Time.point, bs = “fs”). Here, “fs” (standing for “factor smooth”) is the basis function. We are replacing the random intercept with the factor smooth, as this included the intercept shift implicitly (as the factor smooth is not centered).

#While including non-linear differences over plant mass is important, the models thus far have only included one non-linearity per time point, rather than looking at individual variability in each treatment over plant mass, per time point Therefore, we can replace the random slope of s(Time.point, Treatment, bs = “re”) with an edit made to the random factor smooth: s(plant.mass..g, Time.point, by = Treatment, bs = “fs”). This is replacing the random slope because the difference between treatment conditions are taken into account by the (non-centered) factor smooth. That is, the random factor smooth incorporates a non-centered smooth per treatment condition per time point, which accounts for both the random intercept and random slope, as well as non-linear differences between categories across plant mass.

m4.gam=gam(DOC..mg.L~ Treatment + s(plant.mass..g, by = Treatment) + s(Time.point, Treatment, bs = "re") + s(plant.mass..g, Time.point, bs = "fs"), data = DOC.df, method = "REML")
summary(m4.gam)

m5.gam=gam(DOC..mg.L~ Treatment + s(plant.mass..g, by = Treatment)  + s(plant.mass..g, Time.point, by = Treatment, bs = "fs"), data = DOC.df, method = "REML")
summary(m5.gam)

AIC(m4.gam, m5.gam)

#now lets account the for positively skewed data with gamma distribution and log link. Gamma distributions have variance as a quadratic function of the mean.
#There variance is not constant and the data is heteroscedastic...transforming seems to only account for one of those. Gamma works best since if we  expect to see a small value of DOC we should also expect only a small amount of variability in observed values. On the other hand, if we expect a huge value of DOC, we should expect a lot of variability.
m6.gam=gam(DOC..mg.L ~ Treatment + s(plant.mass..g, by= Treatment) + s(plant.mass..g, Time.point, by= Treatment, bs="fs"), family= Gamma(link="log"), data=DOC.df2, method="REML")
summary(m6.gam)

AIC(m4.gam, m5.gam, m6.gam)

###now we seem to have created a model that fit the original question, how does burning and loading affect DOC while accounting for variation in the random effect of sampling period...let's play with the model to see if we can get a better fit using AIC as our guide

#choose a k value
m7.gam=gam(DOC..mg.L ~ Treatment  + s(plant.mass..g, by=Treatment, k=12) + s(plant.mass..g, Time.point, by=Treatment, bs="fs",k=12), family= Gamma(link="log"), data=DOC.df2, select= T, method="REML")

#better fit with less
m8.gam=gam(DOC..mg.L ~ Treatment  + s(plant.mass..g, by=Treatment, k=8) + s(plant.mass..g, Time.point, by=Treatment, bs="fs",k=8), family= Gamma(link="log"), data=DOC.df2, select= T, method="REML")

AIC(m7.gam, m8.gam)

#remove potential redundancies
m9.gam=gam(DOC..mg.L ~ Treatment  + s(plant.mass..g, Time.point, by=Treatment, bs="fs",k=8), family= Gamma(link="log"), data=DOC.df2, select= T, method="REML")

AIC(m8.gam, m9.gam)

m10.gam=gam(DOC..mg.L ~ Treatment  + s(plant.mass..g, Time.point, by=Treatment, bs="fs"), family= Gamma(link="log"), data=DOC.df2, select= T, method="REML")

AIC(m9.gam, m10.gam)
```


```{r}
DOC.df2$oTreatment=relevel(DOC.df2$Treatment, ref="burned" ) 


m11.gam=gam(log(DOC..mg.L) ~ Treatment*Time.point  + s(plant.mass..g, bs="cs") + s(plant.mass..g, by=oTreatment, bs="cs") + s(plant.mass..g, by=oTime.point, bs="cs"), data=DOC.df2, family= gaussian, select= T, method="REML")
```

winner winner ***model 12***
```{r}
m12.gam=gam(DOC..mg.L ~ Treatment*Time.point  + s(plant.mass..g, bs="cs") + s(plant.mass..g, by=oTreatment, bs="cs") + s(plant.mass..g, by=oTime.point, bs="cs"), family= Gamma(link = "log"), data=DOC.df2, select= T, method="REML")
summary(m12.gam)
gam.check(m12.gam,rep=1000)
draw(m12.gam)
#(Intercept): the intercept for burned in T1
#Treatmentunburned: the  unburned – burned DOC in T1.
#T2: the difference in DOC between T2 versus T1 for burned
#T3: the difference in DOC between T3 versus T` for burned.
#T4: the difference in DOC between T4 versus T` for burned.
#unburned:T2: the interaction of unburned and T2, the unburned effect (unburned-burned) in T2  versus the T1 effect in the burned treatment. Also, the T2 effect (T2 – T1) for unburned versus the T2 effect for burned

```


```{r}
m13.gam=gam(log(DOC..mg.L) ~ Treatment*Time.point  + s(plant.mass..g) + s(plant.mass..g, by=Treatment) + s(plant.mass..g, by=Time.point), data=DOC.df2, select= T, method="REML")

m14.gam=gam(log(DOC..mg.L) ~ Treatment*Time.point  + s(plant.mass..g, k=15) + s(plant.mass..g, by=oTreatment, k=15, m=1) + s(plant.mass..g, by=oTime.point, k=15, m=1), data=DOC.df2, select= T, method="REML")

summary(m11.gam)
gam.check(m11.gam,rep=1000)
draw(m12.gam)
concrvity(m12.gam, terms = everything(), type=c("all"), pairwise = T)

test.gam=gam(Time.point ~ Treatment + s(plant.mass..g), data=DOC.df)

AIC(m11.gam, m12.gam, m13.gam, m14.gam)

library(sjPlot)
library(sjmisc)
library(ggplot2)
plot_model(m12.gam, type = "pred")

interaction.plot(x.factor     = DOC.df$Time.point,
                 trace.factor = DOC.df$Treatment,
                 response     = DOC.df$DOC..mg.L,
                 fun = mean,
                 type="b",
                 col=c("black","red","green"),  ### Colors for levels of trace var.
                 pch=c(19, 17, 15),             ### Symbols for levels of trace var.
                 fixed=TRUE,                    ### Order by factor order in data
                 leg.bty = "o")

#Let’s go through each coefficient:



#(Intercept): the intercept for burned in T1)
#Treatmentunburned: the  unburned – burned DOC in T1).
#T2: the difference in DOC between T2 versus T1 for burned
#T3: the difference in DOC between T3 versus T` for burned.
#T4: the difference in DOC between T4 versus T` for burned.
#unburned:T2: the interaction of unburned and T2, the unburned effect (unburned-burned) in T2  versus the T1 effect in the burned treatment Also, the T2 effect (T2 – T1) for unburned versus the T2 effect for burned
#etc.
library(emmeans)
emmeans(m12.gam, ~Treatment)
#The last three coefficients are the most difficult to interpret. We can think of as the additional unburned effect of going from T1 to T2 and as the additional unburned effect going from T1 to T3, to T4



#The first coefficient exp(2.29)= 9.9 mg/L DOC is the intercept i.e., so burned treatment for T1. The second exp(0.13)= 1.14 is the difference between mean DOC of the unburned treatment and the burned treatment. Similarly the third, fourth, and fifth exp(-0.07= 0.93, -0.26= 0.77, -0.059= 0.94) are mean DOC differences between the time points T2-T1, T3-T1, and T4-T1. The sixth, seventh, and eighth are more tricky...they are the added mean DOC for treatment unburned:T2 or T3 or T4 as compared to the intercept. For example, to get the mean DOC for unburned treatment, T2 we do: exp(2.29)+exp(0.13)+exp(-0.07) +exp(-0.20) or 9.87+1.14+0.93+0.82= 12.76 mg/L.

```


```{r}
m12.gam=gam(DOC..mg.L ~ Treatment  + s(plant.mass..g, by=Treatment) + s(plant.mass..g, Time.point, bs="fs"), family= Gamma(link="log"), data=DOC.df, select= T, method="REML")
#This just confims that Gamma distribution is a better fit
m13.gam=gam(DOC..mg.L ~ Treatment  + s(plant.mass..g, Time.point, by=Treatment, bs="fs", k=12), family= gaussian(link="identity"), data=DOC.df, select= T, method="REML")
summary(m13.gam)

m14.gam=gam(DOC..mg.L ~ Treatment  + s(plant.mass..g, Time.point, by=Treatment, bs="fs", k=12), family= Gamma(link="identity"), data=DOC.df, select= T, method="REML")

#Setting fs just for time point with by level treatment
m15.gam=gam(DOC..mg.L ~ Treatment  + s(plant.mass..g, by=Treatment) +s(plant.mass..g, Time.point, bs="fs"), family= Gamma(link="inverse"), data=DOC.df, select= T, method="REML")
summary(m13.gam)

m16.gam=m11.gam=gam(DOC..mg.L ~ Treatment  + s(plant.mass..g, by=oTreatment, bs="fs", k=12) + s(plant.mass..g, Time.point, bs="fs"), family= Gamma(link="log"), data=DOC.df2, select= T, method="REML")

m17.gam=gamm(DOC..mg.L~Treatment + s(plant.mass..g) ,data=DOC.df,random=list(Time.point=~1),
          correlation=corAR1())
summary(m17.gam$gam)
draw(m17.gam$gam)
gam.check(m17.gam$gam)



contrasts(DOC.df2$oTreatment) <- "contr.treatment"

library(lme4)
m18.glmer=glm(log(DOC..mg.L) ~ Treatment+ plant.mass..g + (1 | Time.point), family=gaussian, data=DOC.df)
Anova(hoops, type="III")
summary(m18.gam)
gam.check(m18.gam, rep=1000)



concurvity(m18.gam, full = T)
install.packages("MuMIn")
library(MuMIn)
options(na.action=na.fail)
dredge(m11.gam)

#additive m16 comparison
AIC(m17.gam, m18.gam)
summary(m11.gam)
anova(m16.gam,m11.gam,test="F")


termplot(exp(m16.gam))

DOC_pred <- data.frame(
  DOC=DOC.df$DOC..mg.L,
  fitted_values= fitted_values(m11.gam, scale = "response")
)

ggplot(DOC_pred)+
  geom_point(aes(x=fitted_values.plant.mass..g,y=DOC,color=fitted_values.Treatment,shape=fitted_values.Time.point))+
  geom_line(aes(x= fitted_values.plant.mass..g, y=fitted_values.fitted, color=fitted_values.Treatment))

AIC(m11.gam, m17.gam)

ggplot(DOC.df)+
  geom_point(aes(x=plant.mass..g, y=Treatment))

```


```{r}
#we can see what this looks like
library(visreg)
visreg(m11.gam, xvar = "plant.mass..g",
       by = "Treatment", data = DOC.df2,
       method = "REML", gg=T)
gam.check(m11.gam, resid=T)
summary(m11.gam)
#exp(2.12999)=8.41
#the conditional mean when all the explanatory variables are 0: burned treatment has a mean DOC of 8.41 
#Unburned mean DOC is exp(-0.02413)= 0.976 less than the burned treatment

#If the outcome is skewed and always positive, it can be modeled using the gamma distribution. The link function is log() to be consistent with the previous linear model, thus the model is modeling the following.

#For example, having unburned = - decreases the log arithmetic mean outcome by -0.02413. The exponentiated coefficient is the factor by which the arithmetic mean outcome on the original scale is multiplied, i.e., if unburned = -, the arithmetic mean on the original scale is 0.98 times lower. This model assumes multiplicative effects on the original outcome by the predictors?

#Concurvity refers to  the situation where a smooth term can be approximated by some combination of the others.
concurvity(m11.gam, full = T)

library(psych)
pairs.panels(DOC.df, 
             method = "pearson", # correlation method
             hist.col = "#00AFBB",
             density = TRUE,  # show density plots
             ellipses = FALSE # show correlation ellipses
             )

?concrvity


```

UVBIO files and plots
```{r}
##### grab files in a list
UVBio.files <- list.files(path="/Users/tobyspiegel2/Desktop/My_pyromania/Pyromania/data/UVBIO", pattern = "csv$", full.names = T)
UVBio.files

##### what are the file names, sans extensions using package 'tools'
file.names<-file_path_sans_ext(list.files(path="/Users/tobyspiegel2/Desktop/My_pyromania/Pyromania/data/UVBIO", pattern = "csv$", full.names = F))
file.names


############ formatting all data in for loop
  for(i in 1:length(UVBio.files))
    {
  data<-read.csv(UVBio.files[i], sep=",") #skip 13 rows where standards are
  data<-data[,c(1,3,4)] # removed columns we don't need
  data$File<-UVBio.files[i]
  colnames(data)<-c("Tank", "DOC..mg.L", "TN..mg.L", "File") 
  data$Tank<-as.character(data$Tank)
  data$Treatment<-IDs$Treatment # add treatment info
  data$plant.mass..g<-IDs$plant.mass..g # add plant biomass info
  make.names(assign(paste(file.names[i], sep=""), data)) # make the file name the name of new df for loop df
  }
########## this is the end of the loop

ls() #see all dfs you've made, the above will be df matching their file names

#Combine files from loop to single df
UVBIO.df<-rbind(DOC_NoUV_T1, DOC_UV_T1, DOC_NoUV_T2, DOC_UV_T2, DOC_NoUV_T3, DOC_UV_T3)

# make new factors for filtered (F/NF) and UV (+/-)
# ** caution! Make sure this matches sheet layout after the loop!

UVBIO.df$Filter.Trt<-rep(c("Filtered", "Unfiltered"), each=30) # repeat 30 times
UVBIO.df$UV.Trt<-rep(c("NoUV", "UV"), each=60) # repeat 60 times

# check tank names in DF and make sure they are what you think they are (i.e 1-30 but w/ weird names)
Tank.fix<-rep(c(1:30), times=12) # repeat 12 times to fix all the strange tank names 

#compare tank IDS
df.test<-cbind(Tank.fix, UVBIO.df$Tank) # yep!

UVBIO.df$Tank<-as.factor(Tank.fix) #replace old tank names

# extract out the file names
UVBIO.df$File <- UVBIO.df$File<-substr(UVBIO.df$File, 63, 77)  # extract sample names
UVBIO.df$DOC..mg.L<-gsub("NPOC:","", UVBIO.df$DOC..mg.L)
UVBIO.df$DOC..mg.L<- gsub("mg/L", "", UVBIO.df$DOC..mg.L)
UVBIO.df$TN..mg.L<-gsub("TN:","", UVBIO.df$TN..mg.L)
UVBIO.df$TN..mg.L<- gsub("mg/L", "", UVBIO.df$TN..mg.L)

#convert DOC and TN to numeric
UVBIO.df$DOC..mg.L<-as.numeric(as.character(UVBIO.df$DOC..mg.L))
UVBIO.df$TN..mg.L<- as.numeric(as.character(UVBIO.df$TN..mg.L))

# add a time point
# if equals DOC_UV_T1_111721 then, T1, if not then "nothing"
UVBIO.df$Time.point<- as.factor(ifelse(UVBIO.df$File=="DOC_UV_T1.csv", "T1",
  ifelse(UVBIO.df$File=="DOC_NoUV_T1.csv", "T1",
          ifelse(UVBIO.df$File=="DOC_UV_T2.csv", "T2",
                ifelse(UVBIO.df$File=="DOC_NoUV_T2.csv", "T2", "T3")))))

#rearrange
UVBIO.df<- UVBIO.df %>% 
  dplyr::select(File, Time.point, Treatment, Filter.Trt, UV.Trt, Tank, plant.mass..g, DOC..mg.L, TN..mg.L)


# make levels for plotting and stats
# add in starting DOC and TN
# original data is... DOC_T0, DOC_T1, DOC_T2, DOC_T3, DOC_T4 -- but no need for DOC T0 and T4
# repeat 4x to account for the 4 treatments in each tank
DOC_T1.start<-rep(DOC_T1$DOC..mg.L, times=4)
DOC_T2.start<-rep(DOC_T2$DOC..mg.L, times=4)
DOC_T3.start<-rep(DOC_T3$DOC..mg.L, times=4)

TN_T1.start<-rep(DOC_T1$TN..mg.L, times=4)
TN_T2.start<-rep(DOC_T2$TN..mg.L, times=4)
TN_T3.start<-rep(DOC_T3$TN..mg.L, times=4)

# compile and add in as a new column
UVBIO.df$Start.DOC<-c(DOC_T1.start, DOC_T2.start, DOC_T3.start)
UVBIO.df$Start.TN<-c(TN_T1.start, TN_T2.start, TN_T3.start)

UVBIO.df$Burn.Filt.UV<-interaction(UVBIO.df$Treatment, UVBIO.df$Filter.Trt, UVBIO.df$UV.Trt)
UVBIO.df$Filt.UV<-interaction(UVBIO.df$Filter.Trt, UVBIO.df$UV.Trt)

```
Calculate photo, microbe, and total degradation:
```{r}
#+UV/+Bio=A
#-UV/+Bio=B
#+UV/-Bio=C
#-UV/-Bio (NoUV,Filtered)=D

#This is calculating % decrease ((control-treatment)/control)*100

#photodegradation

photo.df=data.frame(UVBIO.df[UVBIO.df$Filt.UV=="Filtered.UV",]$Time.point, UVBIO.df[UVBIO.df$Filt.UV=="Filtered.UV",]$Treatment,
                    UVBIO.df[UVBIO.df$Filt.UV=="Filtered.UV",]$Tank,
                    UVBIO.df[UVBIO.df$Filt.UV=="Filtered.UV",]$plant.mass..g,
                    UVBIO.df[UVBIO.df$Filt.UV=="Filtered.UV",]$DOC..mg.L-UVBIO.df[UVBIO.df$Filt.UV=="Filtered.NoUV",]$DOC..mg.L,
                    (100*(UVBIO.df[UVBIO.df$Filt.UV=="Filtered.UV",]$DOC..mg.L-UVBIO.df[UVBIO.df$Filt.UV=="Filtered.NoUV",]$DOC..mg.L)/(abs(UVBIO.df[UVBIO.df$Filt.UV=="Filtered.NoUV",]$DOC..mg.L))))
photo.df$type="photo"
names(photo.df)[1]="Time.point"
names(photo.df)[2]="Treatment"
names(photo.df)[3]="Tank"
names(photo.df)[4]="plant.mass..g"
names(photo.df)[5]="abs.change.DOC"
names(photo.df)[6]="percent.change.DOC"


#Microbe decomp
microbe.df=data.frame(UVBIO.df[UVBIO.df$Filt.UV=="Unfiltered.NoUV",]$Time.point,
                      UVBIO.df[UVBIO.df$Filt.UV=="Unfiltered.NoUV",]$Treatment,
                      UVBIO.df[UVBIO.df$Filt.UV=="Unfiltered.NoUV",]$Tank,
                      UVBIO.df[UVBIO.df$Filt.UV=="Unfiltered.NoUV",]$plant.mass..g,
                    UVBIO.df[UVBIO.df$Filt.UV=="Unfiltered.NoUV",]$DOC..mg.L-UVBIO.df[UVBIO.df$Filt.UV=="Filtered.NoUV",]$DOC..mg.L,
                    (100*(UVBIO.df[UVBIO.df$Filt.UV=="Unfiltered.NoUV",]$DOC..mg.L-UVBIO.df[UVBIO.df$Filt.UV=="Filtered.NoUV",]$DOC..mg.L)/(abs(UVBIO.df[UVBIO.df$Filt.UV=="Filtered.NoUV",]$DOC..mg.L))))
microbe.df$type="microbe"
names(microbe.df)[1]="Time.point"
names(microbe.df)[2]="Treatment"
names(microbe.df)[3]="Tank"
names(microbe.df)[4]="plant.mass..g"
names(microbe.df)[5]="abs.change.DOC"
names(microbe.df)[6]="percent.change.DOC"


#Total decomp= A
total.df=data.frame(UVBIO.df[UVBIO.df$Filt.UV=="Unfiltered.UV",]$Time.point,
                    UVBIO.df[UVBIO.df$Filt.UV=="Unfiltered.UV",]$Treatment,
                    UVBIO.df[UVBIO.df$Filt.UV=="Unfiltered.UV",]$Tank,
                    UVBIO.df[UVBIO.df$Filt.UV=="Unfiltered.UV",]$plant.mass..g,
                    UVBIO.df[UVBIO.df$Filt.UV=="Unfiltered.UV",]$DOC..mg.L-UVBIO.df[UVBIO.df$Filt.UV=="Filtered.NoUV",]$DOC..mg.L,
                     (100*(UVBIO.df[UVBIO.df$Filt.UV=="Unfiltered.UV",]$DOC..mg.L-UVBIO.df[UVBIO.df$Filt.UV=="Filtered.NoUV",]$DOC..mg.L)/(abs(UVBIO.df[UVBIO.df$Filt.UV=="Filtered.NoUV",]$DOC..mg.L))))
total.df$type="total"
names(total.df)[1]="Time.point"
names(total.df)[2]="Treatment"
names(total.df)[3]="Tank"
names(total.df)[4]="plant.mass..g"
names(total.df)[5]="abs.change.DOC"
names(total.df)[6]="percent.change.DOC"


#merge degra.df time points into one dataframe
degra.df=rbind(photo.df, microbe.df, total.df)

#make sure we have factors
degra.df=degra.df%>%
    mutate_if(is.character,as.factor)

#make new column of ordered factors
degra.df=mutate(degra.df, oTreatment= ordered(Treatment, levels= c("burned","unburned")))%>%
  mutate(degra.df, oTime.point= ordered(Time.point, levels= c("T1", "T2", "T3", "T4")))%>%
  mutate(degra.df, otype= ordered(type, levels= c("photo", "microbe", "total")))


```

UVBIO Absolute Change Plots
```{r}
#Unburned treatment degradation
unburned.degra.plot=ggplot(degra.df[(degra.df$Treatment=="unburned"),])+ 
   geom_point(aes(x=plant.mass..g,y=abs.change.DOC,color=type),alpha=0.5)+
  geom_smooth(aes(x=plant.mass..g, y=abs.change.DOC, color=type), method="loess", alpha=0.1)+
  facet_grid(~Time.point)+
  scale_color_manual(values = c("springgreen1", "gold", "midnightblue")) + 
  ggtitle("Degradation: unburned") +
  ylab(expression(paste(Delta, " DOC mg/L"))) +
  xlab("plant material (g)")+
  theme_cowplot(12)
unburned.degra.plot

extract.legend2 <- get_legend(
  # create some space to the left of the legend
  unburned.degra.plot + theme(legend.box.margin = margin(0, 0, 0, 10), legend.title=element_blank()))


#Burned degradation
burned.degra.plot=ggplot(degra.df[(degra.df$Treatment=="burned"),])+ 
   geom_point(aes(x=plant.mass..g,y=abs.change.DOC,color=type),alpha=0.5)+
  geom_smooth(aes(x=plant.mass..g, y=abs.change.DOC, color=type), method="loess", alpha=0.1)+
  facet_grid(~Time.point)+
  scale_color_manual(values = c("springgreen1", "gold", "midnightblue")) + 
  ggtitle("Degradation: burned") +
  xlab("plant material (g)")+
  ylab(expression(paste(Delta, " DOC mg/L"))) +
  theme_cowplot(12)
burned.degra.plot

#combine them
degra.plots=plot_grid(unburned.degra.plot + theme(legend.position = "none",legend.title=element_blank()),
          burned.degra.plot + theme(legend.position = "none"),
          extract.legend2,
          labels = c("a)", "b)"),
          ncol=3, rel_widths = c(8,8,3))

plot_grid(
  ggdraw(add_sub(degra.plots, "Fig 2. Three degradation pathways of dissolved organic carbon (DOC) concentrations across three time points during a seven \nday incubation period for each treatment. \n'Microbe' represents the change in DOC due to microbial degradation, 'photo' represents the change in DOC due to photodegradation, and 'total' represents the change in \nDOC due to both microbial and photodegradation.", x=0.01, hjust=0)), ncol = 1)

degra.plots
ggsave("figures/Fig.2.UVBio.degra_type.plots.pdf", height=5, width=15)
```

UVBIO Percent (decrease) Change Plots
```{r}
#Unburned treatment degradation
perc.unburned.degra.plot=ggplot(degra.df[(degra.df$Treatment=="unburned"),])+ 
   geom_point(aes(x=plant.mass..g,y=percent.change.DOC,color=type),alpha=0.5)+
  geom_smooth(aes(x=plant.mass..g, y=percent.change.DOC, color=type), method="loess", alpha=0.1)+
  facet_grid(~Time.point)+
  scale_color_manual(values = c("springgreen1", "gold", "midnightblue")) + 
  ggtitle("Degradation: unburned") +
  ylab(expression(paste("%", Delta, "DOC (mg/L)"))) +
  xlab("plant material (g)")+
  theme_cowplot(12)+
  theme(legend.title=element_blank())
perc.unburned.degra.plot

extract.legend2 <- get_legend(
  # create some space to the left of the legend
  unburned.degra.plot + theme(legend.box.margin = margin(0, 0, 0, 10), legend.title=element_blank()))


#Burned degradation
perc.burned.degra.plot=ggplot(degra.df[(degra.df$Treatment=="burned"),])+ 
   geom_point(aes(x=plant.mass..g,y=percent.change.DOC,color=type),alpha=0.5)+
  geom_smooth(aes(x=plant.mass..g, y=percent.change.DOC, color=type), method="loess", alpha=0.1)+
  facet_grid(~Time.point)+
  scale_color_manual(values = c("springgreen1", "gold", "midnightblue")) + 
  ggtitle("Degradation: burned") +
  xlab("plant material (g)")+
  ylab(expression(paste("%", Delta, "DOC (mg/L)"))) +
  theme_cowplot(12)
burned.degra.plot

#combine them
perc.degra.plots=plot_grid(perc.unburned.degra.plot + theme(legend.position = "none", legend.title=element_blank()), perc.burned.degra.plot + theme(legend.position = "none"),
          extract.legend2,
          labels = c("a)", "b)"),
          ncol=3, rel_widths = c(15,15,3))

plot_grid(
  ggdraw(add_sub(perc.degra.plots, "Fig 2. Three degradation pathways of dissolved organic carbon (DOC) across three time points during a seven \nday incubation period for both treatments. Negative values indicate % DOC loss with 'microbe' representing \nmicrobial degradation, 'photo' representing photodegradation, and 'total' representing both microbial and \nphotodegradation. All positive values indiciate % DOC increase.", x=0.01, hjust=0)), ncol = 1)

degra.plots
ggsave("figures/Fig.2.UVBio.perc.degra_type.plots.pdf", height=5, width=10)

```

UVBIO analysis
```{r}
#fit complex model 
uv.m1.gam=gam(percent.change.DOC ~ Treatment*type*Time.point + s(plant.mass..g, by=oTreatment) + s(plant.mass..g, by=oTime.point) + s(plant.mass..g, by= otype), data=degra.df, method="REML", select= T)
summary(uv.m1.gam)
gam.check(uv.m1.gam, rep = 1000)
draw(uv.m1.gam)

uv.m2.gam=gam(percent.change.DOC ~ Treatment*type*Time.point + s(plant.mass..g)+ s(plant.mass..g, by=Treatment) + s(plant.mass..g, by=Time.point) + s(plant.mass..g, by= type), data=degra.df, method="REML", select= T)
summary(uv.m2.gam)
gam.check(uv.m2.gam, rep=100)

#better to not order the factors
AIC(uv.m1.gam, uv.m2.gam)

uv.m3.gam=gam(percent.change.DOC ~ Treatment*type*Time.point + s(plant.mass..g, k=15)+ s(plant.mass..g, by=Treatment, k=15) + s(plant.mass..g, by=Time.point, k=15) + s(plant.mass..g, by= type, k=15), data=degra.df, method="REML", select= T)
summary(uv.m3.gam)

#knots are good
AIC(uv.m1.gam, uv.m2.gam, uv.m3.gam)

uv.m4.gam=gam(percent.change.DOC ~ Treatment*type*Time.point + s(plant.mass..g, k=15)+ s(plant.mass..g, by=Treatment, k=15, m=1) + s(plant.mass..g, by=Time.point, k=15, m=1) + s(plant.mass..g, by= type, k=15, m=1), data=degra.df, method="REML", select= T)
summary(uv.m4.gam) 
gam.check(uv.m4.gam, rep=1000)

#more penalties are good
AIC(uv.m1.gam, uv.m2.gam, uv.m3.gam, uv.m4.gam)

uv.m5.gam=gam((percent.change.DOC/100) ~ Treatment*type*Time.point + s(plant.mass..g, k=15)+ s(plant.mass..g, by=Treatment, k=15, m=1) + s(plant.mass..g, by=Time.point, k=15, m=1) + s(plant.mass..g, by= type, k=15, m=1), data=degra.df, method="REML", select= T)
summary(uv.m5.gam) 



uv.m6.gam=gam(abs.value.DOC~ Treatment:type + s(plant.mass..g, Treatment, by=type, bs="fs") + s(plant.mass..g, Time.point, by=Treatment, bs="fs"), family=tw(link = "log"), data=degra.df, method="REML")
summary(uv.m6.gam)


uv.m7.gam=gam(abs.value.DOC~ Treatment + type + s(plant.mass..g, Treatment, by=type, bs="fs") + s(plant.mass..g, Time.point, by=Treatment, bs="fs"), family=tw(link = "log"), data=degra.df, method="REML")
summary(uv.m7.gam)

uv.m8.gam=uv.m7.gam=gam(abs.value.DOC~ Treatment + type + s(plant.mass..g, Treatment, by=type, bs="fs") + s(plant.mass..g, Time.point, by=Treatment, bs="fs"), family=tw(link = "log"), data=degra.df, method="REML")
summary(uv.m8.gam)

uv.m9.gam=gam(percent.change.DOC~ Treatment*type*Time.point + s(plant.mass..g, type, by=Treatment) + s(plant.mass..g, by=type) + s(plant.mass..g, by=Time.point), 
data=degra.df, select= T, method="REML")

summary(uv.m9.gam)

AIC(uv.m6.gam,uv.m7.gam, uv.m8.gam, uv.m9.gam)


class(degra.df$percent.change.DOC)











```

Sage and Willow Decomp data
```{r}
#load files and rearrange 
decomp.df=read.csv("/Users/tobyspiegel2/Desktop/GitHub/Pyromania/data/decomp.weights.csv")
names(decomp.df)[8]= "change"
names(decomp.df)[9]= "percent.change"
decomp.df=decomp.df[-c(61:82), ] 

#make a duplicate dataframe and convert % to decimal
decomp2.df=data.frame(decomp.df)
decomp2.df$percent.change=abs(decomp2.df$percent.change/100)
#transform
decomp2.df=decomp2.df%>% 
 mutate(
    across(c(9),
           .fns = ~asin(sqrt(.))))

```

Plant Decomp Plots
```{r}
#Unburned treatment degradation
perc.unburned.decomp.plot=ggplot(decomp.df[(decomp.df$treatment=="unburned"),])+ 
  geom_point(aes(x=plant.specific.mass..g,y=percent.change,color=plant.type),alpha=0.5)+
  geom_smooth(aes(x=plant.specific.mass..g, y=percent.change, color=plant.type), method="loess", alpha=0.1)+
  scale_color_manual(values = c("springgreen1", "gold")) + 
  ggtitle("Degradation: unburned") +
  ylab(expression(paste("% mass loss (g)"))) +
  xlab("plant specific mass (g)")+
  theme_cowplot(12)+
  theme(legend.title=element_blank())
perc.unburned.decomp.plot


extract.legend3 <- get_legend(
  # create some space to the left of the legend
  perc.unburned.decomp.plot + theme(legend.box.margin = margin(0, 0, 0, 10), legend.title=element_blank()))


#Burned degradation
perc.burned.decomp.plot=ggplot(decomp.df[(decomp.df$treatment=="burned"),])+ 
   geom_point(aes(x=plant.specific.mass..g,y=percent.change,color=plant.type),alpha=0.5)+
  geom_smooth(aes(x=plant.specific.mass..g, y=percent.change, color=plant.type), method="loess", alpha=0.1)+
  scale_color_manual(values = c("springgreen1", "gold")) + 
  ggtitle("Degradation: burned") +
  xlab("plant specific mass (g)")+
  ylab(expression(paste("% mass loss (g)"))) +
  theme_cowplot(12)
burned.degra.plot

#combine them
perc.decomp.plots=plot_grid(perc.unburned.decomp.plot + theme(legend.position = "none", legend.title=element_blank()), perc.burned.decomp.plot + theme(legend.position = "none"),
          extract.legend3,
          labels = c("a)", "b)"),
          ncol=3, rel_widths = c(15,15,3))

plot_grid(
  ggdraw(add_sub(perc.decomp.plots, "Fig 4. Total decomposition by plant type for both treatments.", x=0.01, hjust=0)), ncol = 1)

degra.plots
ggsave("figures/Fig.3.perc.decomp_type.plots.pdf", height=5, width=10)










```










