---
title: "Pyromania part 2"
author: "C Wall"
date: "4/20/2022"
output:
  html_document:
    code_folding: hide
    toc: yes
    toc_depth: 4
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '4'
---

Pyromania data for zooplanktona and chlorophyll
```{r setup chunk, setup, include = FALSE, cache=FALSE, message=FALSE, warning=FALSE}
if (!require('knitr')) install.packages('knitr'); library('knitr')
knitr::opts_chunk$set(warning=FALSE, message=FALSE, fig.align='center')

# load packages
if (!require("pacman")) install.packages("pacman") # for rapid install if not in library

# use pacman to load all the packages you are missing!
pacman::p_load('knitr', 'lme4', 'lmerTest', 'tidyverse', 'magrittr', 'effects', 'plyr', 'dplyr', 
               'plotrix', 'car',"gridExtra", "cowplot", "tools", "doBy", "ggplot2", "nlme", "reshape2",
               "mgcv", "vegan")

rm(list=ls())

```

### Zooplankton
integrating the zooplankton counting data and code from Jon into the markdown.

```{r}
plank<-read.csv("data/zooplankton/Pyro_Master zoop data.csv")
names(plank)

plank<-  plyr::rename(plank, c("TANK" = "Tank", "DATE.COLLECTED" = "Date.collected",
                             "X.COUNTED"= "Number.counted", "COUNTED.ON"= "Count.date",
                             "COUNTED.BY" = "Counted.by", "SPECIES" = "Species",
                             "X..OF.INDIVIDUALS" = "Number.of.individ"))



vols<-read.csv("data/zooplankton/Pyro_plankton.volume.csv")
names(vols)<-c("Date.collected","Time.point","Treatment","Plant.mass..g","Tank","Volume.sampled..mL")

# fixing dates
vols$Date.collected<-as.factor(as.POSIXct(vols$Date.collected, format="%m/%d/%Y"))
plank$Date.collected<-as.factor(plank$Date.collected)

# fixing dates that have wrong year
plank$Date.collected[plank$Date.collected=="2022-11-03"]<-"2021-11-03"
plank$Date.collected[plank$Date.collected=="2022-11-15"]<-"2021-11-15"
plank$Date.collected[plank$Date.collected=="2022-12-06"]<-"2021-12-06"

#drop levels
plank<-droplevels(plank)
#inspect table
table(plank$Date.collected, plank$Time.point)

zoop<-merge(plank, vols, by=c("Tank","Date.collected","Time.point"), all=T)
levels(as.factor(zoop$Date.collected))
summary(zoop)

table(zoop$Time.point, zoop$Tank)
table(zoop$Counted.by, zoop$Tank)

levels(as.factor(zoop$Species))

# rename species
zoop<-zoop %>%
  mutate(Species = fct_recode(`Species`,
                              "Mosquito"    = "Mosquito Larvae",
                              "Mosquito"    = "Mosquito Pupae ?",
                              "Mosquito"    = "Mosquito larvae",
                              "Mayfly"    = "Mayfly larvae",
                              "Mayfly"    = "Mayfly larva",
                              "Ephipium"  = "Epliphium"))

levels(as.factor(zoop$Species))


zoop$spp <- casefold(zoop$Species, upper = FALSE)
levels(as.factor(zoop$spp))
str(zoop)

# calculate density
# originally as mL of volume samples, multiply by 1000 to get planton per liter
zoop$Density<-1000*zoop$Number.of.individ/zoop$Volume.sampled..mL

levels(as.factor(zoop$Date.collected))

table(zoop$Tank[zoop$Date.collected=="2021-11-03"], zoop$spp[zoop$Date.collected=="2021-11-03"])

# reorder columns and export
zoop<- zoop %>% select(Time.point, Date.collected, Treatment, Plant.mass..g, Tank, spp, Density)

write.csv(zoop, "data/zooplankton/Pyro_zoop_cleaned.csv")
#############################################
```


```{r, zooplankton summary}
z.df<-zoop

z<-summaryBy(Density ~ Tank + Date.collected + Time.point + Treatment + Plant.mass..g +
               spp, data = z.df, FUN = mean)
```


```{r, Daphnia}
# Daphnia

z1<-pivot_wider(z, names_from="spp", values_from="Density.mean")
z1[is.na(z1)]<-0
names(z1)[21]<-"burst_daphnia"
z1$all_daphnia<-z1$daphnia+z1$burst_daphnia

## Plot
p1<-ggplot(z1,aes(y=all_daphnia, x=Plant.mass..g, color = factor(Treatment))) +
  geom_point(size=2)+
  facet_grid(rows=vars(Date.collected), scales="free_y")+
  labs(x = "G plants added", y="Density (#/L)", title = "Daphnia")+
   geom_smooth(method = loess)
p1
z1$Plant.mass..g<-as.numeric(z1$Plant.mass..g)
z1$Treatment<-as.factor(z1$Treatment)

timepoint<-"T2"
M1 <- gam(all_daphnia ~ s(Plant.mass..g, k=5, bs="tp") +
          s(Plant.mass..g, Treatment, k=5, bs="re"), data=subset(z1, Time.point %in% timepoint), method="REML", family="gaussian")
M2 <- gam(all_daphnia ~ s(Plant.mass..g, k=5, bs="tp"), data=subset(z1, Time.point %in% timepoint), method="REML", family="gaussian")

AIC(M1,M2)
summary(M2)
summary(M1)

# T0
  # No difference between Daphnia abundance along burned/unburned gradients
  # No effect of plant mass on Daphnia abundance p=0.83
# T1
  #No difference between Daphnia abundance along burned/unburned gradients
  # No effect of plant mass on Daphnia abundance p=0.06
# T2
  # No difference between Daphnia abundance along burned/unburned gradients
  # SIGNIFICANT effect of plant mass on Daphnia abundance p=0.04
# T3
  # SIGNIFICANT difference between Daphnia abundance along burned/unburned gradients plantmass*treatment, p=0.009
# T4
  # No difference between Daphnia abundance along burned/unburned gradients
  # No effect of plant mass on Daphnia abundance p=0.13
```


```{r, Mosquito}
#Mosquito
p2<-ggplot(z1,aes(y=mosquito, x=Plant.mass..g, color = factor(Treatment))) +
  geom_point(size=2)+
  facet_grid(rows=vars(Date.collected), scales="free_y")+
  labs(x = "G plants added",y="Density (#/L)", title = "Mosquitoes")+
  geom_smooth(method = loess)
p2

timepoint<-"T4"
M3 <- gam(mosquito ~ s(Plant.mass..g, k=5, bs="tp") +
            s(Plant.mass..g, Treatment, k=12, bs="re"), data=subset(z1, Time.point %in% timepoint), method="REML", family="gaussian")
M4 <- gam(mosquito ~ s(Plant.mass..g, k=5, bs="tp"), data=subset(z1, Time.point %in% timepoint), method="REML", family="gaussian")

AIC(M3,M4) 
summary(M3) 
summary(M4) 

# T0
  # No mosquitos
# T1
  #SIGNIFICANT difference between mosquito abundance along burned/unburned gradients plantmass*treatment, p=0.0004
# T2
  #SIGNIFICANT difference between mosquito abundance along burned/unburned gradients plantmass*treatment, p=0.004
# T3
  # SIGNIFICANT difference between mosquito abundance along burned/unburned gradients plantmass*treatment, p=0.008
# T4
  # SIGNIFICANT difference between mosquito abundance along burned/unburned gradients plantmass*treatment, p=0.01
```


```{r, Calanoid}
#Calanoid
p3<-ggplot(z1,aes(y=calanoid, x=Plant.mass..g, color = factor(Treatment))) +
  geom_point(size=2, aes(colour=factor(Treatment)))+
  facet_grid(rows=vars(Date.collected), scales="free_y")+
  labs(x = "G plants added",y="Density (#/L)", title = "calanoid")+
  geom_smooth(method = loess)
p3


timepoint<-"T4"
M5 <- gam(calanoid ~ s(Plant.mass..g, k=5, bs="tp") +
            s(Plant.mass..g, Treatment, k=5, bs="re"), data=subset(z1, Time.point %in% timepoint), method="REML", family="gaussian")
M6 <- gam(calanoid ~ s(Plant.mass..g, k=5, bs="tp"), data=subset(z1, Time.point %in% timepoint), method="REML", family="gaussian")

AIC(M5,M6) 
summary(M5) 
summary(M6)
```


```{r, Cyclopoid}
#Cyclopoid
p4<-ggplot(z1,aes(y=cyclopoid, x=Plant.mass..g, color = factor(Treatment))) +
  geom_point(size=2, aes(colour=factor(Treatment)))+
  facet_grid(rows=vars(Date.collected), scales="free_y")+
  labs(x = "G plants added",y="Density (#/L)", title = "cyclopoid")+
  geom_smooth(method = loess)
p4

timepoint<-"T3"
M7 <- gam(cyclopoid ~ s(Plant.mass..g, k=5, bs="tp") +
            s(Plant.mass..g, Treatment, k=5, bs="re"), data=subset(z1, Time.point %in% timepoint), method="REML", family="gaussian")
M8 <- gam(cyclopoid ~ s(Plant.mass..g, k=5, bs="tp"), data=subset(z1, Time.point %in% timepoint), method="REML", family="gaussian")

AIC(M7,M8) 
summary(M7) 
summary(M8)
```


```{r, Kellicottia}
#Kellicottia
p5<-ggplot(z1,aes(y=kellicottia, x=Plant.mass..g, color = factor(Treatment))) +
  geom_point(size=2)+
  facet_grid(rows=vars(Date.collected), scales="free_y")+
  labs(x = "G plants added",y="Density (#/L)", title = "kellicottia")+
  geom_smooth(method = loess)
p5
```


```{r, Nauplii}
#Nauplii
p6<-ggplot(z1,aes(y=nauplii, x=Plant.mass..g, color = factor(Treatment))) +
  geom_point(size=2)+
  facet_grid(rows=vars(Date.collected), scales="free_y")+
  labs(x = "G plants added",y="Density (#/L)", title = "nauplii")+
  geom_smooth(method = loess)
p6

p6<-ggplot(z1,aes(y=chironomid, x=Plant.mass..g, color = factor(Treatment))) +
  geom_point(size=2)+
  facet_grid(rows=vars(Date.collected), scales="free_y")+
  labs(x = "G plants added",y="Density (#/L)", title = "chironomid")+
  geom_smooth(method = loess)
p6

```


```{r}
z2<-summaryBy(Density.mean ~ spp, data = z, FUN = c(mean, max, min))

z3<-subset(z, spp=="calanoid"|spp=="ceriodaphnia"|spp=="chironomid"|spp=="cyclopoid"|
             spp=="daphnia"|spp=="kellicottia"|spp=="keratella"|spp=="mayfly"|spp=="mosquito"|
             spp=="nauplii")
levels(as.factor(z$spp))

p7<-ggplot(z3,aes(fill=spp, y=Density.mean, x=Plant.mass..g)) +
  geom_bar(stat="identity", position="fill", width = 12)+
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  facet_grid(rows=vars(Date.collected), cols=vars(Treatment))+
  labs(x = "Treatment")
p7
```


```{r}
# big stacked plot
p8<-ggplot(z3,aes(fill=spp, y=Density.mean, x=Plant.mass..g)) +
  geom_bar(stat="identity", width = 12)+
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  facet_grid(rows=vars(Date.collected), cols=vars(Treatment), scales="fixed")+
  labs(x = "Treatment")
p8 #position="fill"

z4<-pivot_wider(z3, names_from = spp, values_from = Density.mean)
z4[is.na(z4)]<-0
names(z4)
```


```{r}
PCA1 <- prcomp(subset(z4, Time.point %in% "T1")[,c(6:15)], center = TRUE)
PCA2 <- prcomp(subset(z4, Time.point %in% "T2")[,c(6:15)], center = TRUE)
PCA3 <- prcomp(subset(z4, Time.point %in% "T3")[,c(6:15)], center = TRUE)
PCA4 <- prcomp(subset(z4, Time.point %in% "T4")[,c(6:15)], center = TRUE)
```


```{r, T1 PCA}
#TIME 1
scores1<-as.data.frame(PCA1$x[,c(1,2)])
scores1<-cbind(scores1,as.data.frame(subset(z4, Time.point %in% "T1"))[,c(1,4,5)] )
ecor1<-as.data.frame(PCA1$rotation[,c(1:2)])
jj1<-summary(PCA1)
scores1$mass.rank<-trunc(rank(scores1$Plant.mass..g))


PCplot1<-ggplot() +
  geom_point(data=scores1, aes(PC1, PC2, colour=Treatment, fill=Treatment, size=mass.rank*2), alpha=0.3) + 
  geom_segment(data = ecor1,aes(x = 0, y = 0, xend = PC1*15, yend = PC2*15), 
               arrow = arrow(angle=22.5,length = unit(0.35,"cm"),
                             type = "closed"),linetype=1, size=0.6,colour = "black")+
  geom_text(data = ecor1,aes(PC1*15,PC2*15,label=row.names(ecor1)))+
  ggtitle("Time point 1")+
  labs(x=paste("PC 1 (", format(100 *jj1$importance[2,1], digits=4), "%)", sep=""),
       y=paste("PC 2 (", format(100 *jj1$importance[2,2], digits=4), "%)", sep=""))
PCplot1

adonis(subset(z4, Time.point %in% "T1")[,c(6:15)]~scores1$Treatment*scores1$Plant.mass..g)
```


```{r, T2 PCA}
#TIME 2
scores2<-as.data.frame(PCA2$x[,c(1,2)])
scores2<-cbind(scores2,as.data.frame(subset(z4, Time.point %in% "T2"))[,c(1,4,5)] )
ecor2<-as.data.frame(PCA2$rotation[,c(1:2)])
jj2<-summary(PCA2)
scores2$mass.rank<-trunc(rank(scores2$Plant.mass..g))

PCplot2<-ggplot() +
  geom_point(data=scores2, aes(PC1, PC2, colour=Treatment, fill=Treatment, size=mass.rank), alpha=0.3) + 
  geom_segment(data = ecor2,aes(x = 0, y = 0, xend = PC1*15, yend = PC2*15), 
               arrow = arrow(angle=22.5,length = unit(0.35,"cm"),
                             type = "closed"),linetype=1, size=0.6,colour = "black")+
 geom_text(data = ecor2,aes(PC1*15,PC2*15,label=row.names(ecor2)))+
  ggtitle("Time point 2")+
  labs(x=paste("PC 1 (", format(100 *jj2$importance[2,1], digits=4), "%)", sep=""),
       y=paste("PC 2 (", format(100 *jj2$importance[2,2], digits=4), "%)", sep=""))
PCplot2

adonis(subset(z4, Time.point %in% "T2")[,c(6:15)]~scores2$Treatment*scores2$Plant.mass..g)
```


```{r, T3 PCA}
#TIME 3
scores3<-as.data.frame(PCA3$x[,c(1,2)])
scores3<-cbind(scores3,as.data.frame(subset(z4, Time.point %in% "T3"))[,c(1,4,5)] )
ecor3<-as.data.frame(PCA3$rotation[,c(1:2)])
jj3<-summary(PCA3)
scores3$mass.rank<-trunc(rank(scores3$Plant.mass..g))


PCplot3<-ggplot() +
  geom_point(data=scores3, aes(PC1, PC2, colour=Treatment, fill=Treatment, size=mass.rank), alpha=0.3) + 
  geom_segment(data = ecor3,aes(x = 0, y = 0, xend = PC1*15, yend = PC2*15), 
               arrow = arrow(angle=22.5,length = unit(0.35,"cm"),
                             type = "closed"),linetype=1, size=0.6,colour = "black")+
  geom_text(data = ecor3,aes(PC1*15,PC2*15,label=row.names(ecor3)))+
  ggtitle("Time point 3")+
  labs(x=paste("PC 1 (", format(100 *jj3$importance[2,1], digits=4), "%)", sep=""),
       y=paste("PC 2 (", format(100 *jj3$importance[2,2], digits=4), "%)", sep=""))
PCplot3

adonis(subset(z4, Time.point %in% "T3")[,c(6:15)]~scores3$Treatment*scores3$Plant.mass..g)
```


```{r, T4 PCA}
#TIME 4
scores4<-as.data.frame(PCA4$x[,c(1,2)])
scores4<-cbind(scores4,as.data.frame(subset(z4, Time.point %in% "T4"))[,c(1,4,5)] )
ecor4<-as.data.frame(PCA4$rotation[,c(1:2)])
jj4<-summary(PCA4)
scores4$mass.rank<-trunc(rank(scores4$Plant.mass..g))


PCplot4<-ggplot() +
  geom_point(data=scores4, aes(PC1, PC2, colour=Treatment, fill=Treatment, size=mass.rank), alpha=0.3) + 
  geom_segment(data = ecor4,aes(x = 0, y = 0, xend = PC1*15, yend = PC2*15), 
               arrow = arrow(angle=22.5,length = unit(0.35,"cm"),
                             type = "closed"),linetype=1, size=0.6,colour = "black")+
  geom_text(data = ecor4,aes(PC1*15,PC2*15,label=row.names(ecor4)))+
  ggtitle("Time point 4")+
  labs(x=paste("PC 1 (", format(100 *jj3$importance[2,1], digits=4), "%)", sep=""),
       y=paste("PC 2 (", format(100 *jj3$importance[2,2], digits=4), "%)", sep=""))
PCplot4

adonis(subset(z4, Time.point %in% "T4")[,c(6:15)]~scores4$Treatment*scores4$Plant.mass..g)

```


```{r, PCA hell transform}
# With Hellinger transformations

zoop1<-decostand(subset(z4, Time.point %in% "T1")[,c(6:15)], "hell")
PCA1 <- prcomp(zoop1, center = TRUE)
zoop2<-decostand(subset(z4, Time.point %in% "T2")[,c(6:15)], "hell")
PCA2 <- prcomp(zoop2, center = TRUE)
zoop3<-decostand(subset(z4, Time.point %in% "T3")[,c(6:15)], "hell")
PCA3 <- prcomp(zoop3, center = TRUE)
zoop4<-decostand(subset(z4, Time.point %in% "T4")[,c(6:15)], "hell")
PCA4 <- prcomp(zoop4, center = TRUE)
```


```{r, T1 PCA hell transform}
#TIME 1
scores1<-as.data.frame(PCA1$x[,c(1,2)])
scores1<-cbind(scores1,as.data.frame(subset(z4, Time.point %in% "T1"))[,c(1,4,5)] )
jj1<-summary(PCA1)
ecor1<-as.data.frame(PCA1$rotation[,c(1:2)])
scores1$mass.rank<-trunc(rank(scores1$Plant.mass..g))


PCplot1<-ggplot() +
  geom_point(data=scores1, aes(PC1, PC2, colour=Treatment, fill=Treatment, size=mass.rank*2), alpha=0.3) + 
  geom_segment(data = ecor1,aes(x = 0, y = 0, xend = PC1, yend = PC2), 
               arrow = arrow(angle=22.5,length = unit(0.35,"cm"),
                             type = "closed"),linetype=1, size=0.6,colour = "black")+
  geom_text(data = ecor1,aes(PC1,PC2,label=row.names(ecor1)))+
  ggtitle("Time point 1")+
  labs(x=paste("PC 1 (", format(100 *jj1$importance[2,1], digits=4), "%)", sep=""),
       y=paste("PC 2 (", format(100 *jj1$importance[2,2], digits=4), "%)", sep=""))
PCplot1

apply(zoop1, 1, function(x) !all(x==0)) # Need to remove rows of all 0s for the permanova
adonis(zoop1[-5,]~scores1$Treatment[-5]*scores1$Plant.mass..g[-5])

t1zoop<-dbrda(zoop1~scores1$Treatment*scores1$Plant.mass..g) 
anova(t1zoop)
anova(t1zoop, by="terms", permu=800)



# Significant effect of plant mass
```


```{r, T2 PCA hell transform}
#TIME 2
scores2<-as.data.frame(PCA2$x[,c(1,2)])
scores2<-cbind(scores2,as.data.frame(subset(z4, Time.point %in% "T2"))[,c(1,4,5)] )
ecor2<-as.data.frame(PCA2$rotation[,c(1:2)])
jj2<-summary(PCA2)
scores2$mass.rank<-trunc(rank(scores2$Plant.mass..g))

PCplot2<-ggplot() +
  geom_point(data=scores2, aes(PC1, PC2, colour=Treatment, fill=Treatment, size=mass.rank), alpha=0.3) + 
  geom_segment(data = ecor2,aes(x = 0, y = 0, xend = PC1, yend = PC2), 
               arrow = arrow(angle=22.5,length = unit(0.35,"cm"),
                             type = "closed"),linetype=1, size=0.6,colour = "black")+
  geom_text(data = ecor2,aes(PC1,PC2,label=row.names(ecor2)))+
  ggtitle("Time point 2")+
  labs(x=paste("PC 1 (", format(100 *jj2$importance[2,1], digits=4), "%)", sep=""),
       y=paste("PC 2 (", format(100 *jj2$importance[2,2], digits=4), "%)", sep=""))
PCplot2

t2zoop<-dbrda(zoop2~scores2$Treatment*scores2$Plant.mass..g) 
anova(t2zoop)
anova(t2zoop, by="terms", permu=800)
```


```{r, T3 PCA hell transform}
#TIME 3
scores3<-as.data.frame(PCA3$x[,c(1,2)])
scores3<-cbind(scores3,as.data.frame(subset(z4, Time.point %in% "T3"))[,c(1,4,5)] )
ecor3<-as.data.frame(PCA3$rotation[,c(1:2)])
jj3<-summary(PCA3)
scores3$mass.rank<-trunc(rank(scores3$Plant.mass..g))


PCplot3<-ggplot() +
  geom_point(data=scores3, aes(PC1, PC2, colour=Treatment, fill=Treatment, size=mass.rank), alpha=0.3) + 
  geom_segment(data = ecor3,aes(x = 0, y = 0, xend = PC1, yend = PC2), 
               arrow = arrow(angle=22.5,length = unit(0.35,"cm"),
                             type = "closed"),linetype=1, size=0.6,colour = "black")+
  geom_text(data = ecor3,aes(PC1,PC2,label=row.names(ecor3)))+
  ggtitle("Time point 3")+
  labs(x=paste("PC 1 (", format(100 *jj3$importance[2,1], digits=4), "%)", sep=""),
       y=paste("PC 2 (", format(100 *jj3$importance[2,2], digits=4), "%)", sep=""))
PCplot3

t3zoop<-dbrda(zoop3~scores3$Treatment*scores3$Plant.mass..g) 
anova(t3zoop)
anova(t3zoop, by="terms", permu=800)

```


```{r, T4 PCA hell transform}
#TIME 4
scores4<-as.data.frame(PCA4$x[,c(1,2)])
scores4<-cbind(scores4,as.data.frame(subset(z4, Time.point %in% "T4"))[,c(1,4,5)] )
ecor4<-as.data.frame(PCA4$rotation[,c(1:2)])
jj4<-summary(PCA4)
scores4$mass.rank<-trunc(rank(scores4$Plant.mass..g))


PCplot4<-ggplot() +
  geom_point(data=scores4, aes(PC1, PC2, colour=Treatment, fill=Treatment, size=mass.rank), alpha=0.3) + 
  geom_segment(data = ecor4,aes(x = 0, y = 0, xend = PC1, yend = PC2), 
               arrow = arrow(angle=22.5,length = unit(0.35,"cm"),
                             type = "closed"),linetype=1, size=0.6,colour = "black")+
  geom_text(data = ecor4,aes(PC1,PC2,label=row.names(ecor4)))+
  ggtitle("Time point 4")+
  labs(x=paste("PC 1 (", format(100 *jj3$importance[2,1], digits=4), "%)", sep=""),
       y=paste("PC 2 (", format(100 *jj3$importance[2,2], digits=4), "%)", sep=""))
PCplot4

t4zoop<-dbrda(zoop4~scores4$Treatment*scores4$Plant.mass..g) 
anova(t4zoop)
anova(t4zoop, by="terms", permu=800)


```



### Greenhouse Gas Data
```{r}
rm(list=ls())

GHG<-read.csv("data/GH.gases/Pyro_ghg_d13C.csv")
GHG<-na.omit(GHG) # remove NAs

# set structure
make.fac<-c("Time.point", "Treatment", "Tank", "Gas")
GHG[make.fac] <- lapply(GHG[make.fac], factor) # make all these factors
GHG$plant.mass..g<-as.numeric(GHG$plant.mass..g)

# rename
GHG<- GHG %>% rename("GHG.nM" = "GHGwater..nmol.GHG..L.H2O")

# reorder columns and export
GHG<- GHG %>% select(Time.point, Treatment, plant.mass..g, Tank, Gas, GHG.nM, d13C)

GHG<-GHG[!(GHG$GHG.nM < 0),]
#############################################

```

### GHG isotopes
What does CO2-d13C look like?
```{r CO2 model plots}
############# GHG plots and models
#### CO2
#######-- T0

m1.T0.CO2.d13C<- gam(d13C ~ Treatment +
            s(plant.mass..g, by=Treatment), subset = Time.point=="T0", data = CO2,
            method="REML", family="gaussian")

m2.T0.CO2.d13C<- gam(d13C ~ Treatment +
            s(plant.mass..g), subset = Time.point=="T0", data = CO2,
            method="REML", family="gaussian")

m3.T0.CO2.d13C<- gam(d13C ~
            s(plant.mass..g), subset = Time.point=="T0", data = CO2,
            method="REML", family="gaussian")

CO2.d13C.T0.AIC<-AIC(m1.T0.CO2.d13C, m2.T0.CO2.d13C, m3.T0.CO2.d13C)
#factor and global smooth best

summary(m2.T0.CO2.d13C)
anova.gam(m2.T0.CO2.d13C)
gam.check(m2.T0.CO2.d13C, rep=1000)
draw(m2.T0.CO2.d13C)
concrvity(m2.T0.CO2.d13C)
par(mfrow = c(1, 2))
plot(m2.T0.CO2.d13C, all.terms = TRUE, page=1)

# model predictions
CO2.d13C.diff.T0<-plot_difference(
  m1.T0.CO2.d13C,
  series = plant.mass..g,
  difference = list(Treatment = c("burned", "unburned"))
)

###########  
#plot for the model output on rawdata
CO2.d13C.T0.mod.plot<-
  plot_smooths(
  model = m2.T0.CO2.d13C,
  series = plant.mass..g,
  comparison = Treatment
)  + theme(legend.position = "none") +
  geom_point(data=CO2[(CO2$Time.point=="T0"),], 
             aes(x=plant.mass..g, y=d13C, color=Treatment)) +
  scale_color_manual(values = c("brown1", "mediumseagreen")) +
  ylab(expression(paste(delta^{13}, CO2, " (\u2030, air)"))) +
  xlab("plant material (g)") +
  ggtitle("Time-0") +
  coord_cartesian(ylim=c(-30, 0)) +
  Fig.formatting +
  theme(legend.key.size = unit(1,"line"))

CO2.d13C.T0.mod.plot

#### CO2 
#######-- T1

m1.T1.CO2.d13C<- gam(d13C ~ Treatment +
            s(plant.mass..g, by=Treatment), subset = Time.point=="T1", data = CO2,
            method="REML", family="gaussian")

m2.T1.CO2.d13C<- gam(d13C ~ Treatment +
            s(plant.mass..g), subset = Time.point=="T1", data = CO2,
            method="REML", family="gaussian")

m3.T1.CO2.d13C<- gam(d13C ~
            s(plant.mass..g), subset = Time.point=="T1", data = CO2,
            method="REML", family="gaussian")

CO2.d13C.T1.AIC<-AIC(m1.T1.CO2.d13C, m2.T1.CO2.d13C, m3.T1.CO2.d13C)
#global smooth best

summary(m3.T1.CO2.d13C)
anova.gam(m3.T1.CO2.d13C)
gam.check(m3.T1.CO2.d13C, rep=1000)
draw(m3.T1.CO2.d13C)
concrvity(m3.T1.CO2.d13C)
par(mfrow = c(1, 2))
plot(m3.T1.CO2.d13C, all.terms = TRUE, page=1)

# model predictions
CO2.d13C.diff.T1<-plot_difference(
  m1.T1.CO2.d13C,
  series = plant.mass..g,
  difference = list(Treatment = c("burned", "unburned"))
)

###########  
#plot for the model output on rawdata
CO2.d13C.T1.mod.plot<-
  plot_smooths(
  model = m3.T1.CO2.d13C,
  series = plant.mass..g,
)  + theme(legend.position = "none") +
  geom_point(data=CO2[(CO2$Time.point=="T1"),], 
             aes(x=plant.mass..g, y=d13C, color=Treatment)) +
  scale_color_manual(values = c("brown1", "mediumseagreen")) +
  ylab(expression(paste(delta^{13}, CO2, " (\u2030, air)"))) +
  xlab("plant material (g)") +
  ggtitle("Time-1") +
  coord_cartesian(ylim=c(-30, 0)) +
  Fig.formatting +
  theme(legend.key.size = unit(1,"line"))

CO2.d13C.T1.mod.plot

#### CO2
#######-- T2


m1.T2.CO2.d13C<- gam(d13C ~ Treatment +
            s(plant.mass..g, by=Treatment), subset = Time.point=="T2", data = CO2,
            method="REML", family="gaussian")

m2.T2.CO2.d13C<- gam(d13C ~ Treatment +
            s(plant.mass..g), subset = Time.point=="T2", data = CO2,
            method="REML", family="gaussian")

m3.T2.CO2.d13C<- gam(d13C ~
            s(plant.mass..g), subset = Time.point=="T2", data = CO2,
            method="REML", family="gaussian")

CO2.d13C.T2.AIC<-AIC(m1.T2.CO2.d13C, m2.T2.CO2.d13C, m3.T2.CO2.d13C)
#global smooth best

summary(m3.T2.CO2.d13C)
anova.gam(m3.T2.CO2.d13C)
gam.check(m3.T2.CO2.d13C, rep=1000)
draw(m3.T2.CO2.d13C)
concrvity(m3.T2.CO2.d13C)
par(mfrow = c(1, 2))
plot(m3.T2.CO2.d13C, all.terms = TRUE, page=1)

# model predictions
CO2.d13C.diff.T2<-plot_difference(
  m1.T2.CO2.d13C,
  series = plant.mass..g,
  difference = list(Treatment = c("burned", "unburned"))
)

###########  
#plot for the model output on rawdata
CO2.d13C.T2.mod.plot<-
  plot_smooths(
  model = m3.T2.CO2.d13C,
  series = plant.mass..g,
)  + theme(legend.position = "none") +
  geom_point(data=CO2[(CO2$Time.point=="T2"),], 
             aes(x=plant.mass..g, y=d13C, color=Treatment)) +
  scale_color_manual(values = c("brown1", "mediumseagreen")) +
  ylab(expression(paste(delta^{13}, CO2, " (\u2030, air)"))) +
  xlab("plant material (g)") +
  ggtitle("Time-0") +
  coord_cartesian(ylim=c(-30,0)) +
  Fig.formatting +
  theme(legend.key.size = unit(1,"line"))

CO2.d13C.T2.mod.plot


#### CO2 
#######-- T3

m1.T3.CO2.d13C<- gam(d13C ~ Treatment +
            s(plant.mass..g, by=Treatment), subset = Time.point=="T3", data = CO2,
            method="REML", family="gaussian")

m2.T3.CO2.d13C<- gam(d13C ~ Treatment +
            s(plant.mass..g), subset = Time.point=="T3", data = CO2,
            method="REML", family="gaussian")

m3.T3.CO2.d13C<- gam(d13C ~
            s(plant.mass..g), subset = Time.point=="T3", data = CO2,
            method="REML", family="gaussian")

CO2.d13C.T3.AIC<-AIC(m1.T3.CO2.d13C, m2.T3.CO2.d13C, m3.T3.CO2.d13C)
#factor smooth best

summary(m1.T3.CO2.d13C)
anova.gam(m1.T3.CO2.d13C)
gam.check(m1.T3.CO2.d13C, rep=1000)
draw(m1.T3.CO2.d13C)
concrvity(m1.T3.CO2.d13C)
par(mfrow = c(1, 2))
plot(m1.T3.CO2.d13C, all.terms = TRUE, page=1)

# model predictions
CO2.d13C.diff.T3<-plot_difference(
  m1.T3.CO2.d13C,
  series = plant.mass..g,
  difference = list(Treatment = c("burned", "unburned"))
)

###########  
#plot for the model output on rawdata
CO2.d13C.T3.mod.plot<-
  plot_smooths(
  model = m1.T3.CO2.d13C,
  series = plant.mass..g,
  comparison = Treatment
)  + theme(legend.position = "none") +
  geom_point(data=CO2[(CO2$Time.point=="T3"),], 
             aes(x=plant.mass..g, y=d13C, color=Treatment)) +
  scale_color_manual(values = c("brown1", "mediumseagreen")) +
  ylab(expression(paste(delta^{13}, CO2, " (\u2030, air)"))) +
  xlab("plant material (g)") +
  ggtitle("Time-0") +
  coord_cartesian(ylim=c(-30, 0)) +
  Fig.formatting +
  theme(legend.key.size = unit(1,"line"))

CO2.d13C.T3.mod.plot


# models and raw data
CO2.d13C.model.plots<-plot_grid(
  CO2.d13C.T0.mod.plot+ theme(legend.position= "none") + ggtitle( "Day-0"),
  CO2.d13C.T1.mod.plot+ theme(legend.position= "none") + ggtitle( "Day-10"),
  CO2.d13C.T2.mod.plot+ theme(legend.position= "none") + ggtitle( "Day-31"),
  CO2.d13C.T3.mod.plot+ theme(legend.position= "none") + ggtitle( "Day-59"),
  extract.legend, 
  rel_widths = c(8,8,8,8,3), ncol=5)

### model differences
CO2.d13C.plot.diff<-plot_grid(
  CO2.d13C.diff.T0+ ggtitle("CO2-T0"),
  CO2.d13C.diff.T1+ ggtitle("Day-10"),
  CO2.d13C.diff.T2+ ggtitle("Day-31"),
  CO2.d13C.diff.T3+ ggtitle("Day-59"),
  rel_widths = c(8,8,8,8), ncol=4)

## AIC table
mod.ghg.CO2.d13C<-rep(c("Treatment +s(plant.mass..g, by=Treatment)", 
              "Treatment + s(plant.mass..g)", 
              "s(plant.mass..g)"), times=4)

mod.ghg.d13C.df<- data.frame(mod.ghg.CO2.d13C)

AIC.CO2.d13C<-bind_rows(CO2.d13C.T0.AIC, CO2.d13C.T1.AIC, CO2.d13C.T2.AIC, CO2.d13C.T3.AIC)
AIC.CO2.d13C.mod<-cbind(mod.ghg.d13C.df, AIC.CO2.d13C)
write.csv(AIC.CO2.d13C.mod, "output/AIC models/AIC.CO2.d13C.mod.csv")

```

What does CH4-d13C look like?
```{r CH4 model plots}
############# GHG plots and models
#### CH4
#######-- T0

m1.T0.CH4.d13C<- gam(d13C ~ Treatment +
            s(plant.mass..g, by=Treatment), subset = Time.point=="T0", data = CH4,
            method="REML", family="gaussian")

m2.T0.CH4.d13C<- gam(d13C ~ Treatment +
            s(plant.mass..g), subset = Time.point=="T0", data = CH4,
            method="REML", family="gaussian")

m3.T0.CH4.d13C<- gam(d13C ~
            s(plant.mass..g), subset = Time.point=="T0", data = CH4,
            method="REML", family="gaussian")

CH4.d13C.T0.AIC<-AIC(m1.T0.CH4.d13C, m2.T0.CH4.d13C, m3.T0.CH4.d13C)
# global smooth best

summary(m3.T0.CH4.d13C)
anova.gam(m3.T0.CH4.d13C)
gam.check(m3.T0.CH4.d13C, rep=1000)
draw(m3.T0.CH4.d13C)
concrvity(m3.T0.CH4.d13C)
par(mfrow = c(1, 2))
plot(m3.T0.CH4.d13C, all.terms = TRUE, page=1)

# model predictions
CH4.d13C.diff.T0<-plot_difference(
  m1.T0.CH4.d13C,
  series = plant.mass..g,
  difference = list(Treatment = c("burned", "unburned"))
)

###########  
#plot for the model output on rawdata
CH4.d13C.T0.mod.plot<-
  plot_smooths(
  model = m3.T0.CH4.d13C,
  series = plant.mass..g,
)  + theme(legend.position = "none") +
  geom_point(data=CH4[(CH4$Time.point=="T0"),], 
             aes(x=plant.mass..g, y=d13C, color=Treatment)) +
  scale_color_manual(values = c("brown1", "mediumseagreen")) +
 ylab(expression(paste(delta^{13}, CH4, " (\u2030, air)"))) +
  xlab("plant material (g)") +
  ggtitle("Time-0") +
  coord_cartesian(ylim=c(-50, -42)) +
  Fig.formatting +
  theme(legend.key.size = unit(1,"line"))

CH4.d13C.T0.mod.plot

#### CH4 
#######-- T1

m1.T1.CH4.d13C<- gam(d13C ~ Treatment +
            s(plant.mass..g, by=Treatment), subset = Time.point=="T1", data = CH4,
            method="REML", family="gaussian")

m2.T1.CH4.d13C<- gam(d13C ~ Treatment +
            s(plant.mass..g), subset = Time.point=="T1", data = CH4,
            method="REML", family="gaussian")

m3.T1.CH4.d13C<- gam(d13C ~
            s(plant.mass..g), subset = Time.point=="T1", data = CH4,
            method="REML", family="gaussian")

CH4.d13C.T1.AIC<-AIC(m1.T1.CH4.d13C, m2.T1.CH4.d13C, m3.T1.CH4.d13C)
#global smooth best

summary(m3.T1.CH4.d13C)
anova.gam(m3.T1.CH4.d13C)
gam.check(m3.T1.CH4.d13C, rep=1000)
draw(m3.T1.CH4.d13C)
concrvity(m3.T1.CH4.d13C)
par(mfrow = c(1, 2))
plot(m3.T1.CH4.d13C, all.terms = TRUE, page=1)

# model predictions
CH4.d13C.diff.T1<-plot_difference(
  m1.T1.CH4.d13C,
  series = plant.mass..g,
  difference = list(Treatment = c("burned", "unburned"))
)

###########  
#plot for the model output on rawdata
CH4.d13C.T1.mod.plot<-
  plot_smooths(
  model = m3.T1.CH4.d13C,
  series = plant.mass..g,
)  + theme(legend.position = "none") +
  geom_point(data=CH4[(CH4$Time.point=="T1"),], 
             aes(x=plant.mass..g, y=d13C, color=Treatment)) +
  scale_color_manual(values = c("brown1", "mediumseagreen")) +
  ylab(expression(paste(delta^{13}, CH4, " (\u2030, air)"))) +
  xlab("plant material (g)") +
  ggtitle("Time-1") +
  coord_cartesian(ylim=c(-50, -42)) +
  Fig.formatting +
  theme(legend.key.size = unit(1,"line"))

CH4.d13C.T1.mod.plot

#### CH4
#######-- T2


m1.T2.CH4.d13C<- gam(d13C ~ Treatment +
            s(plant.mass..g, by=Treatment), subset = Time.point=="T2", data = CH4,
            method="REML", family="gaussian")

m2.T2.CH4.d13C<- gam(d13C ~ Treatment +
            s(plant.mass..g), subset = Time.point=="T2", data = CH4,
            method="REML", family="gaussian")

m3.T2.CH4.d13C<- gam(d13C ~
            s(plant.mass..g), subset = Time.point=="T2", data = CH4,
            method="REML", family="gaussian")

CH4.d13C.T2.AIC<-AIC(m1.T2.CH4.d13C, m2.T2.CH4.d13C, m3.T2.CH4.d13C)
#global smooth best

summary(m3.T2.CH4.d13C)
anova.gam(m3.T2.CH4.d13C)
gam.check(m3.T2.CH4.d13C, rep=1000)
draw(m3.T2.CH4.d13C)
concrvity(m3.T2.CH4.d13C)
par(mfrow = c(1, 2))
plot(m3.T2.CH4.d13C, all.terms = TRUE, page=1)

# model predictions
CH4.d13C.diff.T2<-plot_difference(
  m1.T2.CH4.d13C,
  series = plant.mass..g,
  difference = list(Treatment = c("burned", "unburned"))
)

###########  
#plot for the model output on rawdata
CH4.d13C.T2.mod.plot<-
  plot_smooths(
  model = m3.T2.CH4.d13C,
  series = plant.mass..g,
)  + theme(legend.position = "none") +
  geom_point(data=CH4[(CH4$Time.point=="T2"),], 
             aes(x=plant.mass..g, y=d13C, color=Treatment)) +
  scale_color_manual(values = c("brown1", "mediumseagreen")) +
  ylab(expression(paste(delta^{13}, CH4, " (\u2030, air)"))) +
  xlab("plant material (g)") +
  ggtitle("Time-2") +
  coord_cartesian(ylim=c(-50, -42)) +
  Fig.formatting +
  theme(legend.key.size = unit(1,"line"))

CH4.d13C.T2.mod.plot


#### CH4 
#######-- T3

m1.T3.CH4.d13C<- gam(d13C ~ Treatment +
            s(plant.mass..g, by=Treatment), subset = Time.point=="T3", data = CH4,
            method="REML", family="gaussian")

m2.T3.CH4.d13C<- gam(d13C ~ Treatment +
            s(plant.mass..g), subset = Time.point=="T3", data = CH4,
            method="REML", family="gaussian")

m3.T3.CH4.d13C<- gam(d13C ~
            s(plant.mass..g), subset = Time.point=="T3", data = CH4,
            method="REML", family="gaussian")

CH4.d13C.T3.AIC<-AIC(m1.T3.CH4.d13C, m2.T3.CH4.d13C, m3.T3.CH4.d13C)
#factor smooth best

summary(m1.T3.CH4.d13C)
anova.gam(m1.T3.CH4.d13C)
gam.check(m1.T3.CH4.d13C, rep=1000)
draw(m1.T3.CH4.d13C)
concrvity(m1.T3.CH4.d13C)
par(mfrow = c(1, 2))
plot(m1.T3.CH4.d13C, all.terms = TRUE, page=1)

# model predictions
CH4.d13C.diff.T3<-plot_difference(
  m1.T3.CH4.d13C,
  series = plant.mass..g,
  difference = list(Treatment = c("burned", "unburned"))
)

###########  
#plot for the model output on rawdata
CH4.d13C.T3.mod.plot<-
  plot_smooths(
  model = m1.T3.CH4.d13C,
  series = plant.mass..g,
  comparison = Treatment
)  + theme(legend.position = "none") +
  geom_point(data=CH4[(CH4$Time.point=="T3"),], 
             aes(x=plant.mass..g, y=d13C, color=Treatment)) +
  scale_color_manual(values = c("brown1", "mediumseagreen")) +
  ylab(expression(paste(delta^{13}, CH4, " (\u2030, air)"))) +
  xlab("plant material (g)") +
  ggtitle("Time-4") +
  coord_cartesian(ylim=c(-50, -42)) +
  Fig.formatting +
  theme(legend.key.size = unit(1,"line"))

CH4.d13C.T3.mod.plot


# models and raw data
CH4.d13C.model.plots<-plot_grid(
  CH4.d13C.T0.mod.plot+ theme(legend.position= "none") + ggtitle( "Day-0"),
  CH4.d13C.T1.mod.plot+ theme(legend.position= "none") + ggtitle( "Day-10"),
  CH4.d13C.T2.mod.plot+ theme(legend.position= "none") + ggtitle( "Day-31"),
  CH4.d13C.T3.mod.plot+ theme(legend.position= "none") + ggtitle( "Day-59"),
  extract.legend, 
  rel_widths = c(8,8,8,8,3), ncol=5)

### model differences
CH4.d13C.plot.diff<-plot_grid(
  CH4.d13C.diff.T0+ ggtitle("CH4-T0"),
  CH4.d13C.diff.T1+ ggtitle("Day-10"),
  CH4.d13C.diff.T2+ ggtitle("Day-31"),
  CH4.d13C.diff.T3+ ggtitle("Day-59"),
  rel_widths = c(8,8,8,8), ncol=4)

## AIC table
mod.ghg.CH4.d13C<-rep(c("Treatment +s(plant.mass..g, by=Treatment)", 
              "Treatment + s(plant.mass..g)", 
              "s(plant.mass..g)"), times=4)

mod.ghg.d13C.df<- data.frame(mod.ghg.CH4.d13C)

AIC.CH4.d13C<-bind_rows(CH4.d13C.T0.AIC, CH4.d13C.T1.AIC, CH4.d13C.T2.AIC, CH4.d13C.T3.AIC)
AIC.CH4.d13C.mod<-cbind(mod.ghg.d13C.df, AIC.CH4.d13C)
write.csv(AIC.CH4.d13C.mod, "output/AIC models/AIC.CH4.d13C.mod.csv")

```

Compile the greenhouse gas plots
```{r combine CO2CH4.d13C plots}

GHG.plots<-plot_grid(CO2.d13C.model.plots, CH4.d13C.model.plots, ncol=1)
ggsave("figures/GHG.isotope.mod.plots.pdf", height=7, width=12, encod="MacRoman")


GHG.plot.diff<-plot_grid(CO2.d13C.diff.T3, CH4.d13C.diff.T3, ncol=1)
ggsave("figures/GHG.isotope.mod.diff.pdf", height=7, width=4, encod="MacRoman")


```


###Chlorophyll  
import   
- may not be useful...
```{r chlorophyll, eval =FALSE}
## import treatment IDs
chl.dat<- read.csv("data/Pyro_chlorophyll.csv")  
chl.dat<-chl.dat[!(chl.dat$Time.point=="First.round"),] # remove first round from aborted mission

#remove outlier
chl.out.rem<-chl.dat[!(chl.dat$chla..ug.L>=10),]


#plot

chla.T0<-ggplot(chl.dat[(chl.dat$Time.point=="T0"),], aes(x=plant.mass..g, y=chla..ug.L, color=Treatment)) +
  geom_point() +
  scale_color_manual(values = c("brown1", "mediumseagreen")) + 
  geom_smooth(method=loess, aes(fill=Treatment), alpha=0.1) +
  coord_cartesian(ylim=c(0, 20)) +
  ggtitle("Time-0") +
  ylab(expression(paste("chlorophyll", ~(mu*g~L^-1), sep=""))) +
  xlab("plant material (g)") +
  Fig.formatting


chla.T1<-ggplot(chl.dat[(chl.dat$Time.point=="T1"),], aes(x=plant.mass..g, y=chla..ug.L, color=Treatment)) +
  geom_point() +
  scale_color_manual(values = c("brown1", "mediumseagreen")) + 
  geom_smooth(method=loess, aes(fill=Treatment), alpha=0.1) +
  coord_cartesian(ylim=c(0, 20)) +
  ggtitle("Time-1") +
  ylab(expression(paste("chlorophyll", ~(mu*g~L^-1), sep=""))) +
  xlab("plant material (g)") +
  Fig.formatting

chla.T2<-ggplot(chl.dat[(chl.dat$Time.point=="T2"),], aes(x=plant.mass..g, y=chla..ug.L, color=Treatment)) +
  geom_point() +
  scale_color_manual(values = c("brown1", "mediumseagreen")) + 
  geom_smooth(method=loess, aes(fill=Treatment), alpha=0.1) +
  coord_cartesian(ylim=c(0, 20)) +
  ggtitle("Time-2") +
  ylab(expression(paste("chlorophyll", ~(mu*g~L^-1), sep=""))) +
  xlab("plant material (g)") +
  Fig.formatting

chla.T3<-ggplot(chl.dat[(chl.dat$Time.point=="T3"),], aes(x=plant.mass..g, y=chla..ug.L, color=Treatment)) +
  geom_point() +
  scale_color_manual(values = c("brown1", "mediumseagreen")) + 
  geom_smooth(method=loess, aes(fill=Treatment), alpha=0.1) +
  coord_cartesian(ylim=c(0, 20)) +
  ggtitle("Time-3") +
  ylab(expression(paste("chlorophyll", ~(mu*g~L^-1), sep=""))) +
  xlab("plant material (g)") +
  Fig.formatting

chla.T4<-ggplot(chl.dat[(chl.dat$Time.point=="T4"),], aes(x=plant.mass..g, y=chla..ug.L, color=Treatment)) +
  geom_point() +
  scale_color_manual(values = c("brown1", "mediumseagreen")) + 
  geom_smooth(method=loess, aes(fill=Treatment), alpha=0.1) +
  coord_cartesian(ylim=c(0, 20)) +
  ggtitle("Time-4") +
  ylab(expression(paste("chlorophyll", ~(mu*g~L^-1), sep=""))) +
  xlab("plant material (g)") +
  Fig.formatting


chl.plots<-plot_grid(
  chla.T0+ theme(legend.position = "none"),
  chla.T2+ theme(legend.position = "none"),
  chla.T2+ theme(legend.position = "none"),
  chla.T3+ theme(legend.position = "none"),
  chla.T4+ theme(legend.position = "none"),
  extract.legend, 
  rel_widths = c(8,8,8,8,8,3), ncol=6)


chl.plots

ggsave("figures/chla.alltime.pdf", height=5, width=15)



```
  