---
title: "Pyromania"
author: "C Wall"
date: "12/7/2021"
output:
  html_document:
    code_folding: hide
    toc: yes
    toc_depth: 4
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '4'
---

```{r setup chunk, setup, include = FALSE, cache=FALSE, message=FALSE, warning=FALSE}
if (!require('knitr')) install.packages('knitr'); library('knitr')
knitr::opts_chunk$set(warning=FALSE, message=FALSE, fig.align='center')

# load packages
if (!require("pacman")) install.packages("pacman") # for rapid install if not in library

# use pacman to load all the packages you are missing!
pacman::p_load('knitr', 'lme4', 'lmerTest', 'tidyverse', 'magrittr', 'effects', 'plyr', 'dplyr', 
               'plotrix', 'car',"gridExtra", "cowplot", "tools")


```


###YSI  
Time 1 and Time 2: import YSI data and prduce plots of changes in O2% and net ecosystem productivity (NEP) and net ecosystem respiration (NER)  
```{r}
#load YSI data
YSI<-read.csv("data/Pyro_YSI.csv")

# fix date
YSI$Date<-as.character(YSI$Date)
YSI$Date<-as.POSIXct(YSI$Date, format="%m/%d/%y")
YSI$Date<-as.Date(YSI$Date, format="%m/%d/%y")


####### Time 1 change in O2 ################

#separate time points
YSI.T1<- YSI[(YSI$Time.point=="T1"),]

#calculate NEP for T1
T1.Prod<-YSI.T1[(YSI.T1$Date == "2021-11-15"),] # dawn and dusk for 12h period
T1.Dawn1<-T1.Prod[(T1.Prod$Dawn..Dusk == "dawn"),] # dawn-1 measurements
T1.Dusk<-T1.Prod[(T1.Prod$Dawn..Dusk == "dusk"),] # dusk measurements

T1.Dawn2<-YSI.T1[(YSI.T1$Date == "2021-11-16"),] # dawn-2 measurements, following AM

# make new dataframe
T1.O2<-(T1.Dawn1[,c(2,4:6)]) 
T1.O2$dawn1<-T1.Dawn1$DO.percent
T1.O2$dusk1<-T1.Dusk$DO.percent
T1.O2$dawn2<-T1.Dawn2$DO.percent

# NER = dusk - dawn (PM to AM, O2 change of day 1)
# NEP = dusk - dawn (PM to AM, O2 change of day 2)

T1.O2<- mutate(T1.O2, 
                NEP=dusk1 - dawn1,
                NER=dawn2 - dusk1) 

#sort
T1.O2<-T1.O2 %>% 
  arrange(Treatment, plant.mass..g) 


################ ################ ################
####### Time 2 change in O2 ################

#separate time points
YSI.T2<- YSI[(YSI$Time.point=="T2"),]

#calculate NEP for T2
T2.Prod<-YSI.T2[(YSI.T2$Date == "2021-12-06"),] # dawn and dusk for 12h period
T2.Dawn1<-T2.Prod[(T2.Prod$Dawn..Dusk == "dawn"),] # dawn-1 measurements
T2.Dusk<-T2.Prod[(T2.Prod$Dawn..Dusk == "dusk"),] # dusk measurements

T2.Dawn2<-YSI.T2[(YSI.T2$Date == "2021-12-07"),] # dawn-2 measurements, following AM

# make new dataframe
T2.O2<-(T2.Dawn1[,c(2,4:6)]) 
T2.O2$dawn1<-T2.Dawn1$DO.percent
T2.O2$dusk1<-T2.Dusk$DO.percent
T2.O2$dawn2<-T2.Dawn2$DO.percent

T2.O2<- mutate(T2.O2, 
                NEP=dusk1 - dawn1,
                NER=dawn2 - dusk1) 

#sort
T2.O2<-T2.O2 %>% 
  arrange(Treatment, plant.mass..g) 

################ ################ ################
# combine T1 and T2 timepoints
################ ################ ################
O2.tanks<-rbind(T1.O2,T2.O2)
```
  
TIME POINT 1: Change in O2% and NEP and NER --   
make figures of the data for timepoint 1  
```{r}
########## 
Fig.formatting<-(theme_classic()) +
  theme(text=element_text(size=10),
        axis.line=element_blank(),
        legend.text.align = 0,
        legend.text=element_text(size=10),
        #legend.title = element_blank(),
        panel.border = element_rect(fill=NA, colour = "black", size=1),
        aspect.ratio=1, 
        axis.ticks.length=unit(0.25, "cm"),
        axis.text.y=element_text(
          margin=unit(c(0.5, 0.5, 0.5, 0.5), "cm"), colour="black", size=10), 
        axis.text.x=element_text(
          margin=unit(c(0.5, 0.5, 0.5, 0.5), "cm"), colour="black", size=8)) +
  theme(legend.key.size = unit(0.4, "cm")) +
  theme(aspect.ratio=1.3) +
  theme(panel.spacing=unit(c(0, 0, 0, 0), "cm"))

#########################################################
############################################################################
###############################################################################################
###################

# total oxygen % plot for the 3 time points (dawn-dusk-dawn)

T1.AM1<-ggplot(T1.O2, aes(x=plant.mass..g, y=dawn1, color=Treatment)) + 
  geom_point() +
  scale_color_manual(values = c("brown1", "mediumseagreen")) + 
  geom_smooth(method=lm, aes(fill=Treatment), alpha=0.1) +
  geom_hline(yintercept=0, linetype="longdash", color = "gray") +
  ggtitle("T1.dawn1")+
  coord_cartesian(ylim=c(-30, 150)) +
  ylab(expression(paste("O"[2],"%"))) +
  xlab("plant material (g)") +
  Fig.formatting

T1.PM1<-ggplot(T1.O2, aes(x=plant.mass..g, y=dusk1, color=Treatment)) + 
  geom_point() +
  scale_color_manual(values = c("brown1", "mediumseagreen")) + 
  geom_smooth(method=lm, aes(fill=Treatment), alpha=0.1) +
  geom_hline(yintercept=0, linetype="longdash", color = "gray") +
  ggtitle("T1.dusk1")+
  coord_cartesian(ylim=c(-30, 150)) +
  ylab(expression(paste("O"[2],"%"))) +
  xlab("plant material (g)") +
  Fig.formatting

T1.AM2<-ggplot(T1.O2, aes(x=plant.mass..g, y=dawn2, color=Treatment)) + 
  geom_point() +
  scale_color_manual(values = c("brown1", "mediumseagreen")) + 
  geom_smooth(method=lm, aes(fill=Treatment), alpha=0.1) +
  geom_hline(yintercept=0, linetype="longdash", color = "gray") +
  ggtitle("T1.dawn2")+
  coord_cartesian(ylim=c(-30, 150)) +
  ylab(expression(paste("O"[2],"%"))) +
  xlab("plant material (g)") +
  Fig.formatting

extract.legend <- get_legend(
  # create some space to the left of the legend
  T1.AM1 + theme(legend.box.margin = margin(0, 0, 0, 10)))

O2.T1<-plot_grid(
  T1.AM1+ theme(legend.position = "none"), 
  T1.PM1+ theme(legend.position = "none"), 
  T1.AM2+ theme(legend.position = "none"),
  extract.legend, 
  rel_widths = c(8,8,8,3), ncol=4)

ggsave("figures/O2.T1.pdf", height=5, width=9)

#################################
############################################
# net ecosystem production and respiration

#Time 1 NEP
NEP.T1<-ggplot(T1.O2, aes(x=plant.mass..g, y=NEP, color=Treatment)) + 
  geom_point() +
  scale_color_manual(values = c("brown1", "mediumseagreen")) + 
  geom_smooth(method=lm, aes(fill=Treatment), alpha=0.1) +
  geom_hline(yintercept=0, linetype="longdash", color = "gray") +
  ylab(expression(paste("Net Production (", Delta, "O"[2],"%)"))) +
  xlab("plant material (g)")+
  Fig.formatting

#Time 1 NER
NER.T1<-ggplot(T1.O2, aes(x=plant.mass..g, y=NER, color=Treatment)) + 
  geom_point() +
  scale_color_manual(values = c("brown1", "mediumseagreen")) + 
  geom_smooth(method=lm, aes(fill=Treatment), alpha=0.1) +
  geom_hline(yintercept=0, linetype="longdash", color = "gray") +
  ylab(expression(paste("Net Respiration (", Delta, "O"[2],"%)"))) +
  xlab("plant material (g)") +
  Fig.formatting


O2.change.T1<-plot_grid(
  NEP.T1+ theme(legend.position = "none") + ggtitle("Time 1"), 
  NER.T1+ theme(legend.position = "none") + ggtitle(""),
  extract.legend, 
  rel_widths = c(8,8,3), ncol=3)

ggsave("figures/O2.change.T1.pdf", height=5, width=8)
```
  
TIME POINT 2: Change in O2% and NEP and NER --
make figures of the data for timepoint 2
```{r}
############################################################
##############################################################################
#############################################################################################
###################

# total oxygen % plot for the 3 time points (dawn-dusk-dawn)

T2.AM1<-ggplot(T2.O2, aes(x=plant.mass..g, y=dawn1, color=Treatment)) + 
  geom_point() +
  scale_color_manual(values = c("brown1", "mediumseagreen")) + 
  geom_smooth(method=lm, aes(fill=Treatment), alpha=0.1) +
  geom_hline(yintercept=0, linetype="longdash", color = "gray") +
  ggtitle("T2.dawn1")+
  coord_cartesian(ylim=c(-30, 150)) +
  ylab(expression(paste("O"[2],"%"))) +
  xlab("plant material (g)") +
  Fig.formatting

T2.PM1<-ggplot(T2.O2, aes(x=plant.mass..g, y=dusk1, color=Treatment)) + 
  geom_point() +
  scale_color_manual(values = c("brown1", "mediumseagreen")) + 
  geom_smooth(method=lm, aes(fill=Treatment), alpha=0.1) +
  geom_hline(yintercept=0, linetype="longdash", color = "gray") +
  ggtitle("T2.dusk1")+
  coord_cartesian(ylim=c(-30, 150)) +
  ylab(expression(paste("O"[2],"%"))) +
  xlab("plant material (g)") +
  Fig.formatting

T2.AM2<-ggplot(T2.O2, aes(x=plant.mass..g, y=dawn2, color=Treatment)) + 
  geom_point() +
  scale_color_manual(values = c("brown1", "mediumseagreen")) + 
  geom_smooth(method=lm, aes(fill=Treatment), alpha=0.1) +
  geom_hline(yintercept=0, linetype="longdash", color = "gray") +
  ggtitle("T2.dawn2")+
  coord_cartesian(ylim=c(-30, 150)) +
  ylab(expression(paste("O"[2],"%"))) +
  xlab("plant material (g)") +
  Fig.formatting

O2.T2<-plot_grid(
  T2.AM1+ theme(legend.position = "none"), 
  T2.PM1+ theme(legend.position = "none"),
  T2.AM2+ theme(legend.position = "none"),
  extract.legend, 
  rel_widths = c(8,8,8,3), ncol=4)

ggsave("figures/O2.T2.pdf", height=5, width=9)


############################################################
##############################################################################################
# net ecosystem production and respiration

#Time 2 NEP
NEP.T2<-ggplot(T2.O2, aes(x=plant.mass..g, y=NEP, color=Treatment)) + 
  geom_point() +
  scale_color_manual(values = c("brown1", "mediumseagreen")) + 
  geom_smooth(method=lm, aes(fill=Treatment), alpha=0.1) +
  geom_hline(yintercept=0, linetype="longdash", color = "gray") +
  ylab(expression(paste("Net Production (", Delta, "O"[2],"%)"))) +
  xlab("plant material (g)") +
  Fig.formatting

#Time 1 NER
NER.T2<-ggplot(T2.O2, aes(x=plant.mass..g, y=NER, color=Treatment)) + 
  geom_point() +
  scale_color_manual(values = c("brown1", "mediumseagreen")) + 
  geom_smooth(method=lm, aes(fill=Treatment),alpha=0.1) +
  geom_hline(yintercept=0, linetype="longdash", color = "gray") +
  ylab(expression(paste("Net Respiration (", Delta, "O"[2],"%)"))) +
  xlab("plant material (g)") +
  Fig.formatting

O2.change.T2<-plot_grid(
  NEP.T2+ theme(legend.position = "none") + ggtitle("Time 2"),
  NER.T2+ theme(legend.position = "none") + ggtitle(""),
  extract.legend, 
  rel_widths = c(8,8,3), ncol=3)

ggsave("figures/O2.change.T2.pdf", height=5, width=8)


```

###DOC  
import and do a loop to clean up all files and make stacked data in single df
```{r}
## import treatment IDs
IDs<-read.csv("data/treatment.IDs.csv")

##### grab files in a list
Total.DOC.files <- list.files(path="data/DOC", pattern = "csv$", full.names = T)
Total.DOC.files

##### what are the file names, sans extensions using package 'tools'
file.names<-file_path_sans_ext(list.files(path="data/DOC", pattern = "csv$", full.names = F))

############ formatting all data in for loop
  for(i in 1:length(Total.DOC.files))
    {
  data<-read.csv(Total.DOC.files[i], sep=",")
  data<-data[,c(1,3,5)] # removed columns we don't need
  data$File<-Total.DOC.files[i]
  colnames(data)<-c("Tank", "NPOC..mg.L", "TN..mg.L", "File")
  data$Tank<-as.numeric(as.character(data$Tank)) # make the column of samples all numeric
  data <- data[!is.na(as.numeric(as.character(data$Tank))),] # remove all rows that aren't numeric/tanks
  data$Treatment<-IDs$Treatment
  data$plant.mass..g<-IDs$plant.mass..g
  make.names(assign(paste(file.names[i], sep=""), data)) # make the file name the name of new df for loop df
  }
########## this is the end of the loop


ls() #see all dfs you've made, the above will be df matching their file names

#Combine files from loop to single df
DOC.df<-rbind(DOC_T0_11052021, DOC_T1_11172021)

# remove the 9 letters ('^.) at start 
# remove the 4 letters ('.$) at end
DOC.df$File<-gsub('^.........|....$', '', DOC.df$File) 

# if equals DOC_T0_11052021 then, T0, if not then T1
DOC.df$Time.point<- as.factor(ifelse(
  DOC.df$File=="DOC_T0_11052021", "T0", "T1"))

#rearrange
DOC.df<- DOC.df %>% 
  select(File, Time.point, Treatment, Tank, plant.mass..g, NPOC..mg.L, TN..mg.L) 

```

DOC plots
```{r}
NPOC.T0<-ggplot(DOC.df[(DOC.df$Time.point=="T0"),], aes(x=plant.mass..g, y=NPOC..mg.L, color=Treatment)) + 
  geom_point() +
  scale_color_manual(values = c("brown1", "mediumseagreen")) + 
  geom_smooth(method=loess, aes(fill=Treatment), alpha=0.1) +
  coord_cartesian(ylim=c(0, 5)) +
  ggtitle("Time-0") +
  ylab("NPOC (mg/L)") +
  xlab("plant material (g)") +
  Fig.formatting

NPOC.T1<-ggplot(DOC.df[(DOC.df$Time.point=="T1"),], aes(x=plant.mass..g, y=NPOC..mg.L, color=Treatment)) + 
  geom_point() +
  scale_color_manual(values = c("brown1", "mediumseagreen")) + 
  geom_smooth(method=loess, aes(fill=Treatment), alpha=0.1) +
  coord_cartesian(ylim=c(0, 60)) +
  ggtitle("Time-1") +
  ylab("NPOC (mg/L)") +
  xlab("plant material (g)") +
  Fig.formatting
  
NPOC.plots<-plot_grid(
  NPOC.T0+ theme(legend.position = "none"),
  NPOC.T1+ theme(legend.position = "none"),
  extract.legend, 
  rel_widths = c(8,8,3), ncol=3)

ggsave("figures/NPOC.pdf", height=5, width=8)
 

```

Total N plots
```{r}
TN.T0<-ggplot(DOC.df[(DOC.df$Time.point=="T0"),], aes(x=plant.mass..g, y=TN..mg.L, color=Treatment)) + 
  geom_point() +
  scale_color_manual(values = c("brown1", "mediumseagreen")) + 
  geom_smooth(method=loess, aes(fill=Treatment), alpha=0.1) +
  coord_cartesian(ylim=c(0, 2)) +
  ggtitle("Time-0") +
  ylab("TN (mg/L)") +
  xlab("plant material (g)") +
  Fig.formatting

TN.T1<-ggplot(DOC.df[(DOC.df$Time.point=="T1"),], aes(x=plant.mass..g, y=TN..mg.L, color=Treatment)) + 
  geom_point() +
  scale_color_manual(values = c("brown1", "mediumseagreen")) + 
  geom_smooth(method=loess, aes(fill=Treatment), alpha=0.1) +
  coord_cartesian(ylim=c(0, 2)) +
  ggtitle("Time-1") +
  ylab("TN (mg/L)") +
  xlab("plant material (g)") +
  Fig.formatting
  
TN.plots<-plot_grid(
  TN.T0+ theme(legend.position = "none"),
  TN.T1+ theme(legend.position = "none"),
  extract.legend, 
  rel_widths = c(8,8,3), ncol=3)

ggsave("figures/TN.pdf", height=5, width=8)

```

